#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"

#define XCHG_CHAIN "xchg_chains"
#define ROPCHAIN "ropchains"
#define SECTIONS "sections"
#define GADGET_ANALYSIS "gadget_analysis"
#define GADGET_EXTRACTION "gadget_extraction"
#define GADGET_FILTER "gadget_filter"
#define SYMBOL_EXTRACTION "symbol_extraction"
#define XCHG_GRAPH "xchg_graph"
#define LIVENESS_ANALYSIS "liveness_analysis"
#define PROCESSED_INSTR "processed_instr"
#define OBF_STATS "obf_stats"
