# This configuration uses ROP chains, opaque predicates and constants.

# Opaque constants are applied only to a part of the gadgets' addresses
# and branch instructions are not obfuscated.

[general]
avoid_multiversion_symbol = true

[functions.default]
    obfuscation_enabled = true
    opaque_gadget_addresses_enabled = true
    gadget_addresses_obfuscation_percentage = 30
    opaque_predicates_enabled = true
    obfuscate_stack_saved_values = true
    obfuscate_immediate_operand = true
    obfuscate_branch_target = false
    opaque_predicates_algorithm = "multcomp"
    opaque_predicate_use_contextual = true
