/* This program is for testing conflicting names with libc.
 * readelf -s libc.so.6 | grep ' 13 ' |awk '{print $8;}' | cut -d@ -f1 | sort | uniq | awk '{print "DEFINE_FUNC(" $1 ")"}'
 */

#pragma GCC diagnostic ignored "-Wincompatible-library-redeclaration"
#pragma GCC diagnostic ignored "-Wbuiltin-requires-header"

extern int printf(const char *, ...);

#define FUNCS \
DEFINE_FUNC(a64l) \
/* DEFINE_FUNC(abort) */ \
DEFINE_FUNC(abs) \
DEFINE_FUNC(accept) \
DEFINE_FUNC(accept4) \
DEFINE_FUNC(access) \
DEFINE_FUNC(acct) \
DEFINE_FUNC(addmntent) \
DEFINE_FUNC(addseverity) \
DEFINE_FUNC(adjtime) \
DEFINE_FUNC(adjtimex) \
DEFINE_FUNC(__adjtimex) \
DEFINE_FUNC(advance) \
DEFINE_FUNC(alarm) \
DEFINE_FUNC(aligned_alloc) \
DEFINE_FUNC(alphasort) \
DEFINE_FUNC(alphasort64) \
DEFINE_FUNC(argp_error) \
DEFINE_FUNC(argp_failure) \
DEFINE_FUNC(argp_help) \
DEFINE_FUNC(argp_parse) \
DEFINE_FUNC(argp_state_help) \
DEFINE_FUNC(argp_usage) \
DEFINE_FUNC(argz_add) \
DEFINE_FUNC(argz_add_sep) \
DEFINE_FUNC(argz_append) \
DEFINE_FUNC(__argz_count) \
DEFINE_FUNC(argz_count) \
DEFINE_FUNC(argz_create) \
DEFINE_FUNC(argz_create_sep) \
DEFINE_FUNC(argz_delete) \
DEFINE_FUNC(argz_extract) \
DEFINE_FUNC(argz_insert) \
DEFINE_FUNC(__argz_next) \
DEFINE_FUNC(argz_next) \
DEFINE_FUNC(argz_replace) \
DEFINE_FUNC(__argz_stringify) \
DEFINE_FUNC(argz_stringify) \
DEFINE_FUNC(asctime) \
DEFINE_FUNC(asctime_r) \
DEFINE_FUNC(asprintf) \
DEFINE_FUNC(__asprintf) \
DEFINE_FUNC(__asprintf_chk) \
DEFINE_FUNC(__assert) \
DEFINE_FUNC(__assert_fail) \
DEFINE_FUNC(__assert_perror_fail) \
DEFINE_FUNC(atexit) \
DEFINE_FUNC(atof) \
DEFINE_FUNC(atoi) \
DEFINE_FUNC(atol) \
DEFINE_FUNC(atoll) \
DEFINE_FUNC(authdes_create) \
DEFINE_FUNC(authdes_getucred) \
DEFINE_FUNC(authdes_pk_create) \
DEFINE_FUNC(_authenticate) \
DEFINE_FUNC(authnone_create) \
DEFINE_FUNC(authunix_create) \
DEFINE_FUNC(authunix_create_default) \
DEFINE_FUNC(backtrace) \
DEFINE_FUNC(__backtrace) \
DEFINE_FUNC(__backtrace_symbols) \
DEFINE_FUNC(backtrace_symbols) \
DEFINE_FUNC(__backtrace_symbols_fd) \
DEFINE_FUNC(backtrace_symbols_fd) \
DEFINE_FUNC(basename) \
DEFINE_FUNC(bcmp) \
DEFINE_FUNC(bcopy) \
DEFINE_FUNC(bdflush) \
DEFINE_FUNC(bind) \
DEFINE_FUNC(bindresvport) \
DEFINE_FUNC(bindtextdomain) \
DEFINE_FUNC(bind_textdomain_codeset) \
DEFINE_FUNC(brk) \
DEFINE_FUNC(__bsd_getpgrp) \
DEFINE_FUNC(bsd_signal) \
DEFINE_FUNC(bsearch) \
DEFINE_FUNC(btowc) \
DEFINE_FUNC(bzero) \
DEFINE_FUNC(__bzero) \
DEFINE_FUNC(c16rtomb) \
DEFINE_FUNC(c32rtomb) \
DEFINE_FUNC(calloc) \
DEFINE_FUNC(callrpc) \
DEFINE_FUNC(__call_tls_dtors) \
DEFINE_FUNC(canonicalize_file_name) \
DEFINE_FUNC(capget) \
DEFINE_FUNC(capset) \
DEFINE_FUNC(catclose) \
DEFINE_FUNC(catgets) \
DEFINE_FUNC(catopen) \
DEFINE_FUNC(cbc_crypt) \
DEFINE_FUNC(cfgetispeed) \
DEFINE_FUNC(cfgetospeed) \
DEFINE_FUNC(cfmakeraw) \
DEFINE_FUNC(cfree) \
DEFINE_FUNC(cfsetispeed) \
DEFINE_FUNC(cfsetospeed) \
DEFINE_FUNC(cfsetspeed) \
DEFINE_FUNC(chdir) \
DEFINE_FUNC(chflags) \
DEFINE_FUNC(__chk_fail) \
DEFINE_FUNC(chmod) \
DEFINE_FUNC(chown) \
DEFINE_FUNC(chroot) \
DEFINE_FUNC(clearenv) \
DEFINE_FUNC(clearerr) \
DEFINE_FUNC(clearerr_unlocked) \
DEFINE_FUNC(clnt_broadcast) \
DEFINE_FUNC(clnt_create) \
DEFINE_FUNC(clnt_pcreateerror) \
DEFINE_FUNC(clnt_perrno) \
DEFINE_FUNC(clnt_perror) \
DEFINE_FUNC(clntraw_create) \
DEFINE_FUNC(clnt_spcreateerror) \
DEFINE_FUNC(clnt_sperrno) \
DEFINE_FUNC(clnt_sperror) \
DEFINE_FUNC(clnttcp_create) \
DEFINE_FUNC(clntudp_bufcreate) \
DEFINE_FUNC(clntudp_create) \
DEFINE_FUNC(clntunix_create) \
DEFINE_FUNC(clock) \
DEFINE_FUNC(clock_adjtime) \
DEFINE_FUNC(__clock_getcpuclockid) \
DEFINE_FUNC(clock_getcpuclockid) \
DEFINE_FUNC(__clock_getres) \
DEFINE_FUNC(clock_getres) \
DEFINE_FUNC(__clock_gettime) \
DEFINE_FUNC(clock_gettime) \
DEFINE_FUNC(__clock_nanosleep) \
DEFINE_FUNC(clock_nanosleep) \
DEFINE_FUNC(__clock_settime) \
DEFINE_FUNC(clock_settime) \
DEFINE_FUNC(clone) \
DEFINE_FUNC(__clone) \
DEFINE_FUNC(close) \
DEFINE_FUNC(__close) \
DEFINE_FUNC(closedir) \
DEFINE_FUNC(closelog) \
DEFINE_FUNC(__close_nocancel) \
DEFINE_FUNC(__cmsg_nxthdr) \
DEFINE_FUNC(confstr) \
DEFINE_FUNC(__confstr_chk) \
DEFINE_FUNC(connect) \
DEFINE_FUNC(__connect) \
DEFINE_FUNC(copy_file_range) \
DEFINE_FUNC(__copy_grp) \
DEFINE_FUNC(copysign) \
DEFINE_FUNC(copysignf) \
DEFINE_FUNC(copysignl) \
DEFINE_FUNC(creat) \
DEFINE_FUNC(creat64) \
DEFINE_FUNC(create_module) \
DEFINE_FUNC(ctermid) \
DEFINE_FUNC(ctime) \
DEFINE_FUNC(ctime_r) \
DEFINE_FUNC(__ctype_b_loc) \
DEFINE_FUNC(__ctype_get_mb_cur_max) \
DEFINE_FUNC(__ctype_init) \
DEFINE_FUNC(__ctype_tolower_loc) \
DEFINE_FUNC(__ctype_toupper_loc) \
DEFINE_FUNC(cuserid) \
DEFINE_FUNC(__cxa_atexit) \
DEFINE_FUNC(__cxa_at_quick_exit) \
DEFINE_FUNC(__cxa_finalize) \
DEFINE_FUNC(__cxa_thread_atexit_impl) \
DEFINE_FUNC(__cyg_profile_func_enter) \
DEFINE_FUNC(__cyg_profile_func_exit) \
DEFINE_FUNC(daemon) \
DEFINE_FUNC(dcgettext) \
DEFINE_FUNC(__dcgettext) \
DEFINE_FUNC(dcngettext) \
DEFINE_FUNC(__default_morecore) \
DEFINE_FUNC(delete_module) \
DEFINE_FUNC(__deregister_frame) \
DEFINE_FUNC(__deregister_frame_info) \
DEFINE_FUNC(__deregister_frame_info_b) \
DEFINE_FUNC(des_setparity) \
DEFINE_FUNC(dgettext) \
DEFINE_FUNC(__dgettext) \
DEFINE_FUNC(difftime) \
DEFINE_FUNC(dirfd) \
DEFINE_FUNC(dirname) \
DEFINE_FUNC(div) \
DEFINE_FUNC(__divdi3) \
DEFINE_FUNC(_dl_addr) \
DEFINE_FUNC(_dl_catch_error) \
DEFINE_FUNC(_dl_catch_exception) \
DEFINE_FUNC(dl_iterate_phdr) \
DEFINE_FUNC(_dl_mcount_wrapper) \
DEFINE_FUNC(_dl_mcount_wrapper_check) \
DEFINE_FUNC(_dl_signal_error) \
DEFINE_FUNC(_dl_signal_exception) \
DEFINE_FUNC(_dl_sym) \
DEFINE_FUNC(_dl_vsym) \
DEFINE_FUNC(dngettext) \
DEFINE_FUNC(dprintf) \
DEFINE_FUNC(__dprintf_chk) \
DEFINE_FUNC(drand48) \
DEFINE_FUNC(drand48_r) \
DEFINE_FUNC(dup) \
DEFINE_FUNC(dup2) \
DEFINE_FUNC(__dup2) \
DEFINE_FUNC(dup3) \
DEFINE_FUNC(duplocale) \
DEFINE_FUNC(__duplocale) \
DEFINE_FUNC(dysize) \
DEFINE_FUNC(eaccess) \
DEFINE_FUNC(ecb_crypt) \
DEFINE_FUNC(ecvt) \
DEFINE_FUNC(ecvt_r) \
DEFINE_FUNC(endaliasent) \
DEFINE_FUNC(endfsent) \
DEFINE_FUNC(endgrent) \
DEFINE_FUNC(endhostent) \
DEFINE_FUNC(endmntent) \
DEFINE_FUNC(__endmntent) \
DEFINE_FUNC(endnetent) \
DEFINE_FUNC(endnetgrent) \
DEFINE_FUNC(endprotoent) \
DEFINE_FUNC(endpwent) \
DEFINE_FUNC(endrpcent) \
DEFINE_FUNC(endservent) \
DEFINE_FUNC(endsgent) \
DEFINE_FUNC(endspent) \
DEFINE_FUNC(endttyent) \
DEFINE_FUNC(endusershell) \
DEFINE_FUNC(endutent) \
DEFINE_FUNC(endutxent) \
DEFINE_FUNC(envz_add) \
DEFINE_FUNC(envz_entry) \
DEFINE_FUNC(envz_get) \
DEFINE_FUNC(envz_merge) \
DEFINE_FUNC(envz_remove) \
DEFINE_FUNC(envz_strip) \
DEFINE_FUNC(epoll_create) \
DEFINE_FUNC(epoll_create1) \
DEFINE_FUNC(epoll_ctl) \
DEFINE_FUNC(epoll_pwait) \
DEFINE_FUNC(epoll_wait) \
DEFINE_FUNC(erand48) \
DEFINE_FUNC(erand48_r) \
DEFINE_FUNC(err) \
DEFINE_FUNC(__errno_location) \
DEFINE_FUNC(error) \
DEFINE_FUNC(error_at_line) \
DEFINE_FUNC(errx) \
DEFINE_FUNC(ether_aton) \
DEFINE_FUNC(ether_aton_r) \
DEFINE_FUNC(ether_hostton) \
DEFINE_FUNC(ether_line) \
DEFINE_FUNC(ether_ntoa) \
DEFINE_FUNC(ether_ntoa_r) \
DEFINE_FUNC(ether_ntohost) \
DEFINE_FUNC(euidaccess) \
DEFINE_FUNC(eventfd) \
DEFINE_FUNC(eventfd_read) \
DEFINE_FUNC(eventfd_write) \
DEFINE_FUNC(execl) \
DEFINE_FUNC(execle) \
DEFINE_FUNC(execlp) \
DEFINE_FUNC(execv) \
DEFINE_FUNC(execve) \
DEFINE_FUNC(execvp) \
DEFINE_FUNC(execvpe) \
/* DEFINE_FUNC(exit) */ \
/* DEFINE_FUNC(_exit) */ \
/* DEFINE_FUNC(_Exit) */ \
DEFINE_FUNC(explicit_bzero) \
DEFINE_FUNC(__explicit_bzero_chk) \
DEFINE_FUNC(faccessat) \
DEFINE_FUNC(fallocate) \
DEFINE_FUNC(fallocate64) \
DEFINE_FUNC(fanotify_init) \
DEFINE_FUNC(fanotify_mark) \
DEFINE_FUNC(fattach) \
DEFINE_FUNC(__fbufsize) \
DEFINE_FUNC(fchdir) \
DEFINE_FUNC(fchflags) \
DEFINE_FUNC(fchmod) \
DEFINE_FUNC(fchmodat) \
DEFINE_FUNC(fchown) \
DEFINE_FUNC(fchownat) \
DEFINE_FUNC(fclose) \
DEFINE_FUNC(fcloseall) \
DEFINE_FUNC(fcntl) \
DEFINE_FUNC(__fcntl) \
DEFINE_FUNC(fcvt) \
DEFINE_FUNC(fcvt_r) \
DEFINE_FUNC(fdatasync) \
DEFINE_FUNC(__fdelt_chk) \
DEFINE_FUNC(__fdelt_warn) \
DEFINE_FUNC(fdetach) \
DEFINE_FUNC(fdopen) \
DEFINE_FUNC(fdopendir) \
DEFINE_FUNC(__fentry__) \
DEFINE_FUNC(feof) \
DEFINE_FUNC(feof_unlocked) \
DEFINE_FUNC(ferror) \
DEFINE_FUNC(ferror_unlocked) \
DEFINE_FUNC(fexecve) \
DEFINE_FUNC(fflush) \
DEFINE_FUNC(fflush_unlocked) \
DEFINE_FUNC(ffs) \
DEFINE_FUNC(__ffs) \
DEFINE_FUNC(ffsl) \
DEFINE_FUNC(ffsll) \
DEFINE_FUNC(fgetc) \
DEFINE_FUNC(fgetc_unlocked) \
DEFINE_FUNC(fgetgrent) \
DEFINE_FUNC(fgetgrent_r) \
DEFINE_FUNC(fgetpos) \
DEFINE_FUNC(fgetpos64) \
DEFINE_FUNC(fgetpwent) \
DEFINE_FUNC(fgetpwent_r) \
DEFINE_FUNC(fgets) \
DEFINE_FUNC(__fgets_chk) \
DEFINE_FUNC(fgetsgent) \
DEFINE_FUNC(fgetsgent_r) \
DEFINE_FUNC(fgetspent) \
DEFINE_FUNC(fgetspent_r) \
DEFINE_FUNC(fgets_unlocked) \
DEFINE_FUNC(__fgets_unlocked_chk) \
DEFINE_FUNC(fgetwc) \
DEFINE_FUNC(fgetwc_unlocked) \
DEFINE_FUNC(fgetws) \
DEFINE_FUNC(__fgetws_chk) \
DEFINE_FUNC(fgetws_unlocked) \
DEFINE_FUNC(__fgetws_unlocked_chk) \
DEFINE_FUNC(fgetxattr) \
DEFINE_FUNC(fileno) \
DEFINE_FUNC(fileno_unlocked) \
DEFINE_FUNC(finite) \
DEFINE_FUNC(__finite) \
DEFINE_FUNC(finitef) \
DEFINE_FUNC(__finitef) \
DEFINE_FUNC(finitel) \
DEFINE_FUNC(__finitel) \
DEFINE_FUNC(__flbf) \
DEFINE_FUNC(flistxattr) \
DEFINE_FUNC(flock) \
DEFINE_FUNC(flockfile) \
DEFINE_FUNC(_flushlbf) \
DEFINE_FUNC(fmemopen) \
DEFINE_FUNC(fmtmsg) \
DEFINE_FUNC(fnmatch) \
DEFINE_FUNC(fopen) \
DEFINE_FUNC(fopen64) \
DEFINE_FUNC(fopencookie) \
DEFINE_FUNC(fork) \
DEFINE_FUNC(__fork) \
DEFINE_FUNC(__fortify_fail) \
DEFINE_FUNC(fpathconf) \
DEFINE_FUNC(__fpending) \
DEFINE_FUNC(fprintf) \
DEFINE_FUNC(__fprintf_chk) \
DEFINE_FUNC(__fpurge) \
DEFINE_FUNC(fputc) \
DEFINE_FUNC(fputc_unlocked) \
DEFINE_FUNC(fputs) \
DEFINE_FUNC(fputs_unlocked) \
DEFINE_FUNC(fputwc) \
DEFINE_FUNC(fputwc_unlocked) \
DEFINE_FUNC(fputws) \
DEFINE_FUNC(fputws_unlocked) \
DEFINE_FUNC(__frame_state_for) \
DEFINE_FUNC(fread) \
DEFINE_FUNC(__freadable) \
DEFINE_FUNC(__fread_chk) \
DEFINE_FUNC(__freading) \
DEFINE_FUNC(fread_unlocked) \
DEFINE_FUNC(__fread_unlocked_chk) \
DEFINE_FUNC(free) \
DEFINE_FUNC(freeaddrinfo) \
DEFINE_FUNC(freeifaddrs) \
DEFINE_FUNC(freelocale) \
DEFINE_FUNC(__freelocale) \
DEFINE_FUNC(fremovexattr) \
DEFINE_FUNC(freopen) \
DEFINE_FUNC(freopen64) \
DEFINE_FUNC(frexp) \
DEFINE_FUNC(frexpf) \
DEFINE_FUNC(frexpl) \
DEFINE_FUNC(fscanf) \
DEFINE_FUNC(fseek) \
DEFINE_FUNC(fseeko) \
DEFINE_FUNC(fseeko64) \
DEFINE_FUNC(__fsetlocking) \
DEFINE_FUNC(fsetpos) \
DEFINE_FUNC(fsetpos64) \
DEFINE_FUNC(fsetxattr) \
DEFINE_FUNC(fstatfs) \
DEFINE_FUNC(fstatfs64) \
DEFINE_FUNC(fstatvfs) \
DEFINE_FUNC(fstatvfs64) \
DEFINE_FUNC(fsync) \
DEFINE_FUNC(ftell) \
DEFINE_FUNC(ftello) \
DEFINE_FUNC(ftello64) \
DEFINE_FUNC(ftime) \
DEFINE_FUNC(ftok) \
DEFINE_FUNC(ftruncate) \
DEFINE_FUNC(ftruncate64) \
DEFINE_FUNC(ftrylockfile) \
DEFINE_FUNC(fts64_children) \
DEFINE_FUNC(fts64_close) \
DEFINE_FUNC(fts64_open) \
DEFINE_FUNC(fts64_read) \
DEFINE_FUNC(fts64_set) \
DEFINE_FUNC(fts_children) \
DEFINE_FUNC(fts_close) \
DEFINE_FUNC(fts_open) \
DEFINE_FUNC(fts_read) \
DEFINE_FUNC(fts_set) \
DEFINE_FUNC(ftw) \
DEFINE_FUNC(ftw64) \
DEFINE_FUNC(funlockfile) \
DEFINE_FUNC(futimens) \
DEFINE_FUNC(futimes) \
DEFINE_FUNC(futimesat) \
DEFINE_FUNC(fwide) \
DEFINE_FUNC(fwprintf) \
DEFINE_FUNC(__fwprintf_chk) \
DEFINE_FUNC(__fwritable) \
DEFINE_FUNC(fwrite) \
DEFINE_FUNC(fwrite_unlocked) \
DEFINE_FUNC(__fwriting) \
DEFINE_FUNC(fwscanf) \
DEFINE_FUNC(__fxstat) \
DEFINE_FUNC(__fxstat64) \
DEFINE_FUNC(__fxstatat) \
DEFINE_FUNC(__fxstatat64) \
DEFINE_FUNC(__gai_sigqueue) \
DEFINE_FUNC(gai_strerror) \
DEFINE_FUNC(__gconv_get_alias_db) \
DEFINE_FUNC(__gconv_get_cache) \
DEFINE_FUNC(__gconv_get_modules_db) \
DEFINE_FUNC(__gconv_transliterate) \
DEFINE_FUNC(gcvt) \
DEFINE_FUNC(getaddrinfo) \
DEFINE_FUNC(getaliasbyname) \
DEFINE_FUNC(getaliasbyname_r) \
DEFINE_FUNC(getaliasent) \
DEFINE_FUNC(getaliasent_r) \
DEFINE_FUNC(getauxval) \
DEFINE_FUNC(__getauxval) \
DEFINE_FUNC(get_avphys_pages) \
DEFINE_FUNC(getc) \
DEFINE_FUNC(getchar) \
DEFINE_FUNC(getchar_unlocked) \
DEFINE_FUNC(getcontext) \
DEFINE_FUNC(getc_unlocked) \
DEFINE_FUNC(get_current_dir_name) \
DEFINE_FUNC(getcwd) \
DEFINE_FUNC(__getcwd_chk) \
DEFINE_FUNC(getdate) \
DEFINE_FUNC(getdate_r) \
DEFINE_FUNC(getdelim) \
DEFINE_FUNC(__getdelim) \
DEFINE_FUNC(getdirentries) \
DEFINE_FUNC(getdirentries64) \
DEFINE_FUNC(getdomainname) \
DEFINE_FUNC(__getdomainname_chk) \
DEFINE_FUNC(getdtablesize) \
DEFINE_FUNC(getegid) \
DEFINE_FUNC(getentropy) \
DEFINE_FUNC(getenv) \
DEFINE_FUNC(geteuid) \
DEFINE_FUNC(getfsent) \
DEFINE_FUNC(getfsfile) \
DEFINE_FUNC(getfsspec) \
DEFINE_FUNC(getgid) \
DEFINE_FUNC(getgrent) \
DEFINE_FUNC(getgrent_r) \
DEFINE_FUNC(getgrgid) \
DEFINE_FUNC(getgrgid_r) \
DEFINE_FUNC(getgrnam) \
DEFINE_FUNC(getgrnam_r) \
DEFINE_FUNC(getgrouplist) \
DEFINE_FUNC(getgroups) \
DEFINE_FUNC(__getgroups_chk) \
DEFINE_FUNC(gethostbyaddr) \
DEFINE_FUNC(gethostbyaddr_r) \
DEFINE_FUNC(gethostbyname) \
DEFINE_FUNC(gethostbyname2) \
DEFINE_FUNC(gethostbyname2_r) \
DEFINE_FUNC(gethostbyname_r) \
DEFINE_FUNC(gethostent) \
DEFINE_FUNC(gethostent_r) \
DEFINE_FUNC(gethostid) \
DEFINE_FUNC(gethostname) \
DEFINE_FUNC(__gethostname_chk) \
DEFINE_FUNC(getifaddrs) \
DEFINE_FUNC(getipv4sourcefilter) \
DEFINE_FUNC(getitimer) \
DEFINE_FUNC(get_kernel_syms) \
DEFINE_FUNC(getline) \
DEFINE_FUNC(getloadavg) \
DEFINE_FUNC(getlogin) \
DEFINE_FUNC(getlogin_r) \
DEFINE_FUNC(__getlogin_r_chk) \
DEFINE_FUNC(getmntent) \
DEFINE_FUNC(__getmntent_r) \
DEFINE_FUNC(getmntent_r) \
DEFINE_FUNC(getmsg) \
DEFINE_FUNC(get_myaddress) \
DEFINE_FUNC(getnameinfo) \
DEFINE_FUNC(getnetbyaddr) \
DEFINE_FUNC(getnetbyaddr_r) \
DEFINE_FUNC(getnetbyname) \
DEFINE_FUNC(getnetbyname_r) \
DEFINE_FUNC(getnetent) \
DEFINE_FUNC(getnetent_r) \
DEFINE_FUNC(getnetgrent) \
DEFINE_FUNC(getnetgrent_r) \
DEFINE_FUNC(getnetname) \
DEFINE_FUNC(get_nprocs) \
DEFINE_FUNC(get_nprocs_conf) \
DEFINE_FUNC(getopt) \
DEFINE_FUNC(getopt_long) \
DEFINE_FUNC(getopt_long_only) \
DEFINE_FUNC(getpagesize) \
DEFINE_FUNC(__getpagesize) \
DEFINE_FUNC(getpass) \
DEFINE_FUNC(getpeername) \
DEFINE_FUNC(getpgid) \
DEFINE_FUNC(__getpgid) \
DEFINE_FUNC(getpgrp) \
DEFINE_FUNC(get_phys_pages) \
DEFINE_FUNC(getpid) \
DEFINE_FUNC(__getpid) \
DEFINE_FUNC(getpmsg) \
DEFINE_FUNC(getppid) \
DEFINE_FUNC(getpriority) \
DEFINE_FUNC(getprotobyname) \
DEFINE_FUNC(getprotobyname_r) \
DEFINE_FUNC(getprotobynumber) \
DEFINE_FUNC(getprotobynumber_r) \
DEFINE_FUNC(getprotoent) \
DEFINE_FUNC(getprotoent_r) \
DEFINE_FUNC(getpt) \
DEFINE_FUNC(getpublickey) \
DEFINE_FUNC(getpw) \
DEFINE_FUNC(getpwent) \
DEFINE_FUNC(getpwent_r) \
DEFINE_FUNC(getpwnam) \
DEFINE_FUNC(getpwnam_r) \
DEFINE_FUNC(getpwuid) \
DEFINE_FUNC(getpwuid_r) \
DEFINE_FUNC(getrandom) \
DEFINE_FUNC(getresgid) \
DEFINE_FUNC(getresuid) \
DEFINE_FUNC(getrlimit) \
DEFINE_FUNC(__getrlimit) \
DEFINE_FUNC(getrlimit64) \
DEFINE_FUNC(getrpcbyname) \
DEFINE_FUNC(getrpcbyname_r) \
DEFINE_FUNC(getrpcbynumber) \
DEFINE_FUNC(getrpcbynumber_r) \
DEFINE_FUNC(getrpcent) \
DEFINE_FUNC(getrpcent_r) \
DEFINE_FUNC(getrpcport) \
DEFINE_FUNC(getrusage) \
DEFINE_FUNC(gets) \
DEFINE_FUNC(__gets_chk) \
DEFINE_FUNC(getsecretkey) \
DEFINE_FUNC(getservbyname) \
DEFINE_FUNC(getservbyname_r) \
DEFINE_FUNC(getservbyport) \
DEFINE_FUNC(getservbyport_r) \
DEFINE_FUNC(getservent) \
DEFINE_FUNC(getservent_r) \
DEFINE_FUNC(getsgent) \
DEFINE_FUNC(getsgent_r) \
DEFINE_FUNC(getsgnam) \
DEFINE_FUNC(getsgnam_r) \
DEFINE_FUNC(getsid) \
DEFINE_FUNC(getsockname) \
DEFINE_FUNC(getsockopt) \
DEFINE_FUNC(getsourcefilter) \
DEFINE_FUNC(getspent) \
DEFINE_FUNC(getspent_r) \
DEFINE_FUNC(getspnam) \
DEFINE_FUNC(getspnam_r) \
DEFINE_FUNC(getsubopt) \
DEFINE_FUNC(gettext) \
DEFINE_FUNC(gettimeofday) \
DEFINE_FUNC(__gettimeofday) \
DEFINE_FUNC(getttyent) \
DEFINE_FUNC(getttynam) \
DEFINE_FUNC(getuid) \
DEFINE_FUNC(getusershell) \
DEFINE_FUNC(getutent) \
DEFINE_FUNC(getutent_r) \
DEFINE_FUNC(getutid) \
DEFINE_FUNC(getutid_r) \
DEFINE_FUNC(getutline) \
DEFINE_FUNC(getutline_r) \
DEFINE_FUNC(getutmp) \
DEFINE_FUNC(getutmpx) \
DEFINE_FUNC(getutxent) \
DEFINE_FUNC(getutxid) \
DEFINE_FUNC(getutxline) \
DEFINE_FUNC(getw) \
DEFINE_FUNC(getwc) \
DEFINE_FUNC(getwchar) \
DEFINE_FUNC(getwchar_unlocked) \
DEFINE_FUNC(getwc_unlocked) \
DEFINE_FUNC(getwd) \
DEFINE_FUNC(__getwd_chk) \
DEFINE_FUNC(getxattr) \
DEFINE_FUNC(glob) \
DEFINE_FUNC(glob64) \
DEFINE_FUNC(globfree) \
DEFINE_FUNC(globfree64) \
DEFINE_FUNC(glob_pattern_p) \
DEFINE_FUNC(gmtime) \
DEFINE_FUNC(__gmtime_r) \
DEFINE_FUNC(gmtime_r) \
DEFINE_FUNC(gnu_dev_major) \
DEFINE_FUNC(gnu_dev_makedev) \
DEFINE_FUNC(gnu_dev_minor) \
DEFINE_FUNC(gnu_get_libc_release) \
DEFINE_FUNC(gnu_get_libc_version) \
DEFINE_FUNC(grantpt) \
DEFINE_FUNC(group_member) \
DEFINE_FUNC(gsignal) \
DEFINE_FUNC(gtty) \
DEFINE_FUNC(hasmntopt) \
DEFINE_FUNC(hcreate) \
DEFINE_FUNC(hcreate_r) \
DEFINE_FUNC(hdestroy) \
DEFINE_FUNC(hdestroy_r) \
DEFINE_FUNC(__h_errno_location) \
DEFINE_FUNC(herror) \
DEFINE_FUNC(host2netname) \
DEFINE_FUNC(hsearch) \
DEFINE_FUNC(hsearch_r) \
DEFINE_FUNC(hstrerror) \
DEFINE_FUNC(htonl) \
DEFINE_FUNC(htons) \
DEFINE_FUNC(iconv) \
DEFINE_FUNC(iconv_close) \
DEFINE_FUNC(iconv_open) \
DEFINE_FUNC(if_freenameindex) \
DEFINE_FUNC(if_indextoname) \
DEFINE_FUNC(if_nameindex) \
DEFINE_FUNC(if_nametoindex) \
DEFINE_FUNC(imaxabs) \
DEFINE_FUNC(imaxdiv) \
DEFINE_FUNC(index) \
DEFINE_FUNC(inet6_opt_append) \
DEFINE_FUNC(inet6_opt_find) \
DEFINE_FUNC(inet6_opt_finish) \
DEFINE_FUNC(inet6_opt_get_val) \
DEFINE_FUNC(inet6_opt_init) \
DEFINE_FUNC(inet6_option_alloc) \
DEFINE_FUNC(inet6_option_append) \
DEFINE_FUNC(inet6_option_find) \
DEFINE_FUNC(inet6_option_init) \
DEFINE_FUNC(inet6_option_next) \
DEFINE_FUNC(inet6_option_space) \
DEFINE_FUNC(inet6_opt_next) \
DEFINE_FUNC(inet6_opt_set_val) \
DEFINE_FUNC(inet6_rth_add) \
DEFINE_FUNC(inet6_rth_getaddr) \
DEFINE_FUNC(inet6_rth_init) \
DEFINE_FUNC(inet6_rth_reverse) \
DEFINE_FUNC(inet6_rth_segments) \
DEFINE_FUNC(inet6_rth_space) \
DEFINE_FUNC(__inet6_scopeid_pton) \
DEFINE_FUNC(inet_addr) \
DEFINE_FUNC(inet_aton) \
DEFINE_FUNC(inet_lnaof) \
DEFINE_FUNC(inet_makeaddr) \
DEFINE_FUNC(inet_netof) \
DEFINE_FUNC(inet_network) \
DEFINE_FUNC(inet_nsap_addr) \
DEFINE_FUNC(inet_nsap_ntoa) \
DEFINE_FUNC(inet_ntoa) \
DEFINE_FUNC(inet_ntop) \
DEFINE_FUNC(inet_pton) \
DEFINE_FUNC(__inet_pton_length) \
DEFINE_FUNC(initgroups) \
DEFINE_FUNC(init_module) \
DEFINE_FUNC(initstate) \
DEFINE_FUNC(initstate_r) \
DEFINE_FUNC(innetgr) \
DEFINE_FUNC(inotify_add_watch) \
DEFINE_FUNC(inotify_init) \
DEFINE_FUNC(inotify_init1) \
DEFINE_FUNC(inotify_rm_watch) \
DEFINE_FUNC(insque) \
DEFINE_FUNC(__internal_endnetgrent) \
DEFINE_FUNC(__internal_getnetgrent_r) \
DEFINE_FUNC(__internal_setnetgrent) \
DEFINE_FUNC(_IO_adjust_column) \
DEFINE_FUNC(_IO_adjust_wcolumn) \
DEFINE_FUNC(ioctl) \
DEFINE_FUNC(_IO_default_doallocate) \
DEFINE_FUNC(_IO_default_finish) \
DEFINE_FUNC(_IO_default_pbackfail) \
DEFINE_FUNC(_IO_default_uflow) \
DEFINE_FUNC(_IO_default_xsgetn) \
DEFINE_FUNC(_IO_default_xsputn) \
DEFINE_FUNC(_IO_doallocbuf) \
DEFINE_FUNC(_IO_do_write) \
DEFINE_FUNC(_IO_enable_locks) \
DEFINE_FUNC(_IO_fclose) \
DEFINE_FUNC(_IO_fdopen) \
DEFINE_FUNC(_IO_feof) \
DEFINE_FUNC(_IO_ferror) \
DEFINE_FUNC(_IO_fflush) \
DEFINE_FUNC(_IO_fgetpos) \
DEFINE_FUNC(_IO_fgetpos64) \
DEFINE_FUNC(_IO_fgets) \
DEFINE_FUNC(_IO_file_attach) \
DEFINE_FUNC(_IO_file_close) \
DEFINE_FUNC(_IO_file_close_it) \
DEFINE_FUNC(_IO_file_doallocate) \
DEFINE_FUNC(_IO_file_finish) \
DEFINE_FUNC(_IO_file_fopen) \
DEFINE_FUNC(_IO_file_init) \
DEFINE_FUNC(_IO_file_open) \
DEFINE_FUNC(_IO_file_overflow) \
DEFINE_FUNC(_IO_file_read) \
DEFINE_FUNC(_IO_file_seek) \
DEFINE_FUNC(_IO_file_seekoff) \
DEFINE_FUNC(_IO_file_setbuf) \
DEFINE_FUNC(_IO_file_stat) \
DEFINE_FUNC(_IO_file_sync) \
DEFINE_FUNC(_IO_file_underflow) \
DEFINE_FUNC(_IO_file_write) \
DEFINE_FUNC(_IO_file_xsputn) \
DEFINE_FUNC(_IO_flockfile) \
DEFINE_FUNC(_IO_flush_all) \
DEFINE_FUNC(_IO_flush_all_linebuffere) \
DEFINE_FUNC(_IO_fopen) \
DEFINE_FUNC(_IO_fprintf) \
DEFINE_FUNC(_IO_fputs) \
DEFINE_FUNC(_IO_fread) \
DEFINE_FUNC(_IO_free_backup_area) \
DEFINE_FUNC(_IO_free_wbackup_area) \
DEFINE_FUNC(_IO_fsetpos) \
DEFINE_FUNC(_IO_fsetpos64) \
DEFINE_FUNC(_IO_ftell) \
DEFINE_FUNC(_IO_ftrylockfile) \
DEFINE_FUNC(_IO_funlockfile) \
DEFINE_FUNC(_IO_fwrite) \
DEFINE_FUNC(_IO_getc) \
DEFINE_FUNC(_IO_getline) \
DEFINE_FUNC(_IO_getline_info) \
DEFINE_FUNC(_IO_gets) \
DEFINE_FUNC(_IO_init) \
DEFINE_FUNC(_IO_init_marker) \
DEFINE_FUNC(_IO_init_wmarker) \
DEFINE_FUNC(_IO_iter_begin) \
DEFINE_FUNC(_IO_iter_end) \
DEFINE_FUNC(_IO_iter_file) \
DEFINE_FUNC(_IO_iter_next) \
DEFINE_FUNC(_IO_least_wmarker) \
DEFINE_FUNC(_IO_link_in) \
DEFINE_FUNC(_IO_list_lock) \
DEFINE_FUNC(_IO_list_resetlock) \
DEFINE_FUNC(_IO_list_unlock) \
DEFINE_FUNC(_IO_marker_delta) \
DEFINE_FUNC(_IO_marker_difference) \
DEFINE_FUNC(_IO_padn) \
DEFINE_FUNC(_IO_peekc_locked) \
DEFINE_FUNC(ioperm) \
DEFINE_FUNC(iopl) \
DEFINE_FUNC(_IO_popen) \
DEFINE_FUNC(_IO_printf) \
DEFINE_FUNC(_IO_proc_close) \
DEFINE_FUNC(_IO_proc_open) \
DEFINE_FUNC(_IO_putc) \
DEFINE_FUNC(_IO_puts) \
DEFINE_FUNC(_IO_remove_marker) \
DEFINE_FUNC(_IO_seekmark) \
DEFINE_FUNC(_IO_seekoff) \
DEFINE_FUNC(_IO_seekpos) \
DEFINE_FUNC(_IO_seekwmark) \
DEFINE_FUNC(_IO_setb) \
DEFINE_FUNC(_IO_setbuffer) \
DEFINE_FUNC(_IO_setvbuf) \
DEFINE_FUNC(_IO_sgetn) \
DEFINE_FUNC(_IO_sprintf) \
DEFINE_FUNC(_IO_sputbackc) \
DEFINE_FUNC(_IO_sputbackwc) \
DEFINE_FUNC(_IO_sscanf) \
DEFINE_FUNC(_IO_str_init_readonly) \
DEFINE_FUNC(_IO_str_init_static) \
DEFINE_FUNC(_IO_str_overflow) \
DEFINE_FUNC(_IO_str_pbackfail) \
DEFINE_FUNC(_IO_str_seekoff) \
DEFINE_FUNC(_IO_str_underflow) \
DEFINE_FUNC(_IO_sungetc) \
DEFINE_FUNC(_IO_sungetwc) \
DEFINE_FUNC(_IO_switch_to_get_mode) \
DEFINE_FUNC(_IO_switch_to_main_wget_a) \
DEFINE_FUNC(_IO_switch_to_wbackup_are) \
DEFINE_FUNC(_IO_switch_to_wget_mode) \
DEFINE_FUNC(_IO_ungetc) \
DEFINE_FUNC(_IO_un_link) \
DEFINE_FUNC(_IO_unsave_markers) \
DEFINE_FUNC(_IO_unsave_wmarkers) \
DEFINE_FUNC(_IO_vfprintf) \
DEFINE_FUNC(_IO_vfscanf) \
DEFINE_FUNC(_IO_vsprintf) \
DEFINE_FUNC(_IO_wdefault_doallocate) \
DEFINE_FUNC(_IO_wdefault_finish) \
DEFINE_FUNC(_IO_wdefault_pbackfail) \
DEFINE_FUNC(_IO_wdefault_uflow) \
DEFINE_FUNC(_IO_wdefault_xsgetn) \
DEFINE_FUNC(_IO_wdefault_xsputn) \
DEFINE_FUNC(_IO_wdoallocbuf) \
DEFINE_FUNC(_IO_wdo_write) \
DEFINE_FUNC(_IO_wfile_overflow) \
DEFINE_FUNC(_IO_wfile_seekoff) \
DEFINE_FUNC(_IO_wfile_sync) \
DEFINE_FUNC(_IO_wfile_underflow) \
DEFINE_FUNC(_IO_wfile_xsputn) \
DEFINE_FUNC(_IO_wmarker_delta) \
DEFINE_FUNC(_IO_wsetb) \
DEFINE_FUNC(iruserok) \
DEFINE_FUNC(iruserok_af) \
DEFINE_FUNC(isalnum) \
DEFINE_FUNC(__isalnum_l) \
DEFINE_FUNC(isalnum_l) \
DEFINE_FUNC(isalpha) \
DEFINE_FUNC(__isalpha_l) \
DEFINE_FUNC(isalpha_l) \
DEFINE_FUNC(isascii) \
DEFINE_FUNC(__isascii_l) \
DEFINE_FUNC(isastream) \
DEFINE_FUNC(isatty) \
DEFINE_FUNC(isblank) \
DEFINE_FUNC(__isblank_l) \
DEFINE_FUNC(isblank_l) \
DEFINE_FUNC(iscntrl) \
DEFINE_FUNC(__iscntrl_l) \
DEFINE_FUNC(iscntrl_l) \
DEFINE_FUNC(isctype) \
DEFINE_FUNC(__isctype) \
DEFINE_FUNC(isdigit) \
DEFINE_FUNC(__isdigit_l) \
DEFINE_FUNC(isdigit_l) \
DEFINE_FUNC(isfdtype) \
DEFINE_FUNC(isgraph) \
DEFINE_FUNC(__isgraph_l) \
DEFINE_FUNC(isgraph_l) \
DEFINE_FUNC(isinf) \
DEFINE_FUNC(__isinf) \
DEFINE_FUNC(isinff) \
DEFINE_FUNC(__isinff) \
DEFINE_FUNC(isinfl) \
DEFINE_FUNC(__isinfl) \
DEFINE_FUNC(islower) \
DEFINE_FUNC(__islower_l) \
DEFINE_FUNC(islower_l) \
DEFINE_FUNC(isnan) \
DEFINE_FUNC(__isnan) \
DEFINE_FUNC(isnanf) \
DEFINE_FUNC(__isnanf) \
DEFINE_FUNC(isnanl) \
DEFINE_FUNC(__isnanl) \
DEFINE_FUNC(__isoc99_fscanf) \
DEFINE_FUNC(__isoc99_fwscanf) \
DEFINE_FUNC(__isoc99_scanf) \
DEFINE_FUNC(__isoc99_sscanf) \
DEFINE_FUNC(__isoc99_swscanf) \
DEFINE_FUNC(__isoc99_vfscanf) \
DEFINE_FUNC(__isoc99_vfwscanf) \
DEFINE_FUNC(__isoc99_vscanf) \
DEFINE_FUNC(__isoc99_vsscanf) \
DEFINE_FUNC(__isoc99_vswscanf) \
DEFINE_FUNC(__isoc99_vwscanf) \
DEFINE_FUNC(__isoc99_wscanf) \
DEFINE_FUNC(isprint) \
DEFINE_FUNC(__isprint_l) \
DEFINE_FUNC(isprint_l) \
DEFINE_FUNC(ispunct) \
DEFINE_FUNC(__ispunct_l) \
DEFINE_FUNC(ispunct_l) \
DEFINE_FUNC(isspace) \
DEFINE_FUNC(__isspace_l) \
DEFINE_FUNC(isspace_l) \
DEFINE_FUNC(isupper) \
DEFINE_FUNC(__isupper_l) \
DEFINE_FUNC(isupper_l) \
DEFINE_FUNC(iswalnum) \
DEFINE_FUNC(__iswalnum_l) \
DEFINE_FUNC(iswalnum_l) \
DEFINE_FUNC(iswalpha) \
DEFINE_FUNC(__iswalpha_l) \
DEFINE_FUNC(iswalpha_l) \
DEFINE_FUNC(iswblank) \
DEFINE_FUNC(__iswblank_l) \
DEFINE_FUNC(iswblank_l) \
DEFINE_FUNC(iswcntrl) \
DEFINE_FUNC(__iswcntrl_l) \
DEFINE_FUNC(iswcntrl_l) \
DEFINE_FUNC(iswctype) \
DEFINE_FUNC(__iswctype) \
DEFINE_FUNC(__iswctype_l) \
DEFINE_FUNC(iswctype_l) \
DEFINE_FUNC(iswdigit) \
DEFINE_FUNC(__iswdigit_l) \
DEFINE_FUNC(iswdigit_l) \
DEFINE_FUNC(iswgraph) \
DEFINE_FUNC(__iswgraph_l) \
DEFINE_FUNC(iswgraph_l) \
DEFINE_FUNC(iswlower) \
DEFINE_FUNC(__iswlower_l) \
DEFINE_FUNC(iswlower_l) \
DEFINE_FUNC(iswprint) \
DEFINE_FUNC(__iswprint_l) \
DEFINE_FUNC(iswprint_l) \
DEFINE_FUNC(iswpunct) \
DEFINE_FUNC(__iswpunct_l) \
DEFINE_FUNC(iswpunct_l) \
DEFINE_FUNC(iswspace) \
DEFINE_FUNC(__iswspace_l) \
DEFINE_FUNC(iswspace_l) \
DEFINE_FUNC(iswupper) \
DEFINE_FUNC(__iswupper_l) \
DEFINE_FUNC(iswupper_l) \
DEFINE_FUNC(iswxdigit) \
DEFINE_FUNC(__iswxdigit_l) \
DEFINE_FUNC(iswxdigit_l) \
DEFINE_FUNC(isxdigit) \
DEFINE_FUNC(__isxdigit_l) \
DEFINE_FUNC(isxdigit_l) \
DEFINE_FUNC(__ivaliduser) \
DEFINE_FUNC(jrand48) \
DEFINE_FUNC(jrand48_r) \
DEFINE_FUNC(key_decryptsession) \
DEFINE_FUNC(key_decryptsession_pk) \
DEFINE_FUNC(key_encryptsession) \
DEFINE_FUNC(key_encryptsession_pk) \
DEFINE_FUNC(key_gendes) \
DEFINE_FUNC(key_get_conv) \
DEFINE_FUNC(key_secretkey_is_set) \
DEFINE_FUNC(key_setnet) \
DEFINE_FUNC(key_setsecret) \
DEFINE_FUNC(kill) \
DEFINE_FUNC(killpg) \
DEFINE_FUNC(klogctl) \
DEFINE_FUNC(l64a) \
DEFINE_FUNC(labs) \
DEFINE_FUNC(lchmod) \
DEFINE_FUNC(lchown) \
DEFINE_FUNC(lckpwdf) \
DEFINE_FUNC(lcong48) \
DEFINE_FUNC(lcong48_r) \
DEFINE_FUNC(ldexp) \
DEFINE_FUNC(ldexpf) \
DEFINE_FUNC(ldexpl) \
DEFINE_FUNC(ldiv) \
DEFINE_FUNC(lfind) \
DEFINE_FUNC(lgetxattr) \
DEFINE_FUNC(__libc_alloca_cutoff) \
DEFINE_FUNC(__libc_allocate_rtsig) \
DEFINE_FUNC(__libc_allocate_rtsig_pri) \
DEFINE_FUNC(__libc_alloc_buffer_alloc) \
DEFINE_FUNC(__libc_alloc_buffer_copy_) \
DEFINE_FUNC(__libc_alloc_buffer_creat) \
DEFINE_FUNC(__libc_calloc) \
DEFINE_FUNC(__libc_clntudp_bufcreate) \
DEFINE_FUNC(__libc_current_sigrtmax) \
DEFINE_FUNC(__libc_current_sigrtmax_p) \
DEFINE_FUNC(__libc_current_sigrtmin) \
DEFINE_FUNC(__libc_current_sigrtmin_p) \
DEFINE_FUNC(__libc_dlclose) \
DEFINE_FUNC(__libc_dlopen_mode) \
DEFINE_FUNC(__libc_dlsym) \
DEFINE_FUNC(__libc_dlvsym) \
DEFINE_FUNC(__libc_dynarray_at_failur) \
DEFINE_FUNC(__libc_dynarray_emplace_e) \
DEFINE_FUNC(__libc_dynarray_finalize) \
DEFINE_FUNC(__libc_dynarray_resize) \
DEFINE_FUNC(__libc_dynarray_resize_cl) \
DEFINE_FUNC(__libc_fatal) \
DEFINE_FUNC(__libc_fork) \
DEFINE_FUNC(__libc_free) \
DEFINE_FUNC(__libc_ifunc_impl_list) \
DEFINE_FUNC(__libc_init_first) \
DEFINE_FUNC(__libc_longjmp) \
DEFINE_FUNC(__libc_mallinfo) \
DEFINE_FUNC(__libc_malloc) \
DEFINE_FUNC(__libc_mallopt) \
DEFINE_FUNC(__libc_memalign) \
DEFINE_FUNC(__libc_msgrcv) \
DEFINE_FUNC(__libc_msgsnd) \
DEFINE_FUNC(__libc_pread) \
DEFINE_FUNC(__libc_pthread_init) \
DEFINE_FUNC(__libc_pvalloc) \
DEFINE_FUNC(__libc_pwrite) \
DEFINE_FUNC(__libc_realloc) \
DEFINE_FUNC(__libc_reallocarray) \
DEFINE_FUNC(__libc_rpc_getport) \
DEFINE_FUNC(__libc_sa_len) \
DEFINE_FUNC(__libc_scratch_buffer_gro) \
DEFINE_FUNC(__libc_scratch_buffer_set) \
DEFINE_FUNC(__libc_secure_getenv) \
DEFINE_FUNC(__libc_siglongjmp) \
DEFINE_FUNC(__libc_system) \
DEFINE_FUNC(__libc_valloc) \
DEFINE_FUNC(__libc_vfork) \
DEFINE_FUNC(link) \
DEFINE_FUNC(linkat) \
DEFINE_FUNC(listen) \
DEFINE_FUNC(listxattr) \
DEFINE_FUNC(llabs) \
DEFINE_FUNC(lldiv) \
DEFINE_FUNC(llistxattr) \
DEFINE_FUNC(llseek) \
DEFINE_FUNC(localeconv) \
DEFINE_FUNC(localtime) \
DEFINE_FUNC(localtime_r) \
DEFINE_FUNC(lockf) \
DEFINE_FUNC(lockf64) \
DEFINE_FUNC(longjmp) \
DEFINE_FUNC(_longjmp) \
DEFINE_FUNC(__longjmp_chk) \
DEFINE_FUNC(lrand48) \
DEFINE_FUNC(lrand48_r) \
DEFINE_FUNC(lremovexattr) \
DEFINE_FUNC(lsearch) \
DEFINE_FUNC(lseek) \
DEFINE_FUNC(__lseek) \
DEFINE_FUNC(lseek64) \
DEFINE_FUNC(lsetxattr) \
DEFINE_FUNC(lutimes) \
DEFINE_FUNC(__lxstat) \
DEFINE_FUNC(__lxstat64) \
DEFINE_FUNC(madvise) \
DEFINE_FUNC(__madvise) \
DEFINE_FUNC(makecontext) \
DEFINE_FUNC(mallinfo) \
/* DEFINE_FUNC(malloc) */ \
DEFINE_FUNC(malloc_get_state) \
DEFINE_FUNC(malloc_info) \
DEFINE_FUNC(malloc_set_state) \
DEFINE_FUNC(malloc_stats) \
DEFINE_FUNC(malloc_trim) \
DEFINE_FUNC(malloc_usable_size) \
DEFINE_FUNC(mallopt) \
DEFINE_FUNC(mblen) \
DEFINE_FUNC(mbrlen) \
DEFINE_FUNC(__mbrlen) \
DEFINE_FUNC(mbrtoc16) \
DEFINE_FUNC(mbrtoc32) \
DEFINE_FUNC(mbrtowc) \
DEFINE_FUNC(__mbrtowc) \
DEFINE_FUNC(mbsinit) \
DEFINE_FUNC(mbsnrtowcs) \
DEFINE_FUNC(__mbsnrtowcs_chk) \
DEFINE_FUNC(mbsrtowcs) \
DEFINE_FUNC(__mbsrtowcs_chk) \
DEFINE_FUNC(mbstowcs) \
DEFINE_FUNC(__mbstowcs_chk) \
DEFINE_FUNC(mbtowc) \
DEFINE_FUNC(mcheck) \
DEFINE_FUNC(mcheck_check_all) \
DEFINE_FUNC(mcheck_pedantic) \
DEFINE_FUNC(_mcleanup) \
DEFINE_FUNC(mcount) \
DEFINE_FUNC(_mcount) \
DEFINE_FUNC(memalign) \
DEFINE_FUNC(memccpy) \
DEFINE_FUNC(memchr) \
DEFINE_FUNC(memcmp) \
DEFINE_FUNC(memcpy) \
DEFINE_FUNC(__memcpy_by2) \
DEFINE_FUNC(__memcpy_by4) \
DEFINE_FUNC(__memcpy_c) \
DEFINE_FUNC(__memcpy_chk) \
DEFINE_FUNC(__memcpy_g) \
DEFINE_FUNC(memfd_create) \
DEFINE_FUNC(memfrob) \
DEFINE_FUNC(memmem) \
DEFINE_FUNC(memmove) \
DEFINE_FUNC(__memmove_chk) \
DEFINE_FUNC(mempcpy) \
DEFINE_FUNC(__mempcpy) \
DEFINE_FUNC(__mempcpy_by2) \
DEFINE_FUNC(__mempcpy_by4) \
DEFINE_FUNC(__mempcpy_byn) \
DEFINE_FUNC(__mempcpy_chk) \
DEFINE_FUNC(__mempcpy_small) \
DEFINE_FUNC(memrchr) \
DEFINE_FUNC(memset) \
DEFINE_FUNC(__memset_cc) \
DEFINE_FUNC(__memset_ccn_by2) \
DEFINE_FUNC(__memset_ccn_by4) \
DEFINE_FUNC(__memset_cg) \
DEFINE_FUNC(__memset_chk) \
DEFINE_FUNC(__memset_gcn_by2) \
DEFINE_FUNC(__memset_gcn_by4) \
DEFINE_FUNC(__memset_gg) \
DEFINE_FUNC(__merge_grp) \
DEFINE_FUNC(mincore) \
DEFINE_FUNC(mkdir) \
DEFINE_FUNC(mkdirat) \
DEFINE_FUNC(mkdtemp) \
DEFINE_FUNC(mkfifo) \
DEFINE_FUNC(mkfifoat) \
DEFINE_FUNC(mkostemp) \
DEFINE_FUNC(mkostemp64) \
DEFINE_FUNC(mkostemps) \
DEFINE_FUNC(mkostemps64) \
DEFINE_FUNC(mkstemp) \
DEFINE_FUNC(mkstemp64) \
DEFINE_FUNC(mkstemps) \
DEFINE_FUNC(mkstemps64) \
DEFINE_FUNC(mktemp) \
DEFINE_FUNC(__mktemp) \
DEFINE_FUNC(mktime) \
DEFINE_FUNC(mlock) \
DEFINE_FUNC(mlock2) \
DEFINE_FUNC(mlockall) \
DEFINE_FUNC(mmap) \
DEFINE_FUNC(__mmap) \
DEFINE_FUNC(mmap64) \
DEFINE_FUNC(__moddi3) \
DEFINE_FUNC(modf) \
DEFINE_FUNC(modff) \
DEFINE_FUNC(modfl) \
DEFINE_FUNC(__modify_ldt) \
DEFINE_FUNC(modify_ldt) \
DEFINE_FUNC(moncontrol) \
DEFINE_FUNC(monstartup) \
DEFINE_FUNC(__monstartup) \
DEFINE_FUNC(mount) \
DEFINE_FUNC(mprobe) \
DEFINE_FUNC(mprotect) \
DEFINE_FUNC(__mprotect) \
DEFINE_FUNC(mrand48) \
DEFINE_FUNC(mrand48_r) \
DEFINE_FUNC(mremap) \
DEFINE_FUNC(msgctl) \
DEFINE_FUNC(msgget) \
DEFINE_FUNC(msgrcv) \
DEFINE_FUNC(msgsnd) \
DEFINE_FUNC(msync) \
DEFINE_FUNC(mtrace) \
DEFINE_FUNC(munlock) \
DEFINE_FUNC(munlockall) \
DEFINE_FUNC(munmap) \
DEFINE_FUNC(__munmap) \
DEFINE_FUNC(muntrace) \
DEFINE_FUNC(name_to_handle_at) \
DEFINE_FUNC(nanosleep) \
DEFINE_FUNC(__nanosleep) \
DEFINE_FUNC(__netlink_assert_response) \
DEFINE_FUNC(netname2host) \
DEFINE_FUNC(netname2user) \
DEFINE_FUNC(newlocale) \
DEFINE_FUNC(__newlocale) \
DEFINE_FUNC(nfsservctl) \
DEFINE_FUNC(nftw) \
DEFINE_FUNC(nftw64) \
DEFINE_FUNC(ngettext) \
DEFINE_FUNC(nice) \
DEFINE_FUNC(nl_langinfo) \
DEFINE_FUNC(__nl_langinfo_l) \
DEFINE_FUNC(nl_langinfo_l) \
DEFINE_FUNC(nrand48) \
DEFINE_FUNC(nrand48_r) \
DEFINE_FUNC(__nss_configure_lookup) \
DEFINE_FUNC(__nss_database_lookup) \
DEFINE_FUNC(__nss_disable_nscd) \
DEFINE_FUNC(_nss_files_parse_grent) \
DEFINE_FUNC(_nss_files_parse_pwent) \
DEFINE_FUNC(_nss_files_parse_sgent) \
DEFINE_FUNC(_nss_files_parse_spent) \
DEFINE_FUNC(__nss_group_lookup) \
DEFINE_FUNC(__nss_group_lookup2) \
DEFINE_FUNC(__nss_hash) \
DEFINE_FUNC(__nss_hostname_digits_dot) \
DEFINE_FUNC(__nss_hosts_lookup) \
DEFINE_FUNC(__nss_hosts_lookup2) \
DEFINE_FUNC(__nss_lookup) \
DEFINE_FUNC(__nss_lookup_function) \
DEFINE_FUNC(__nss_next) \
DEFINE_FUNC(__nss_next2) \
DEFINE_FUNC(__nss_passwd_lookup) \
DEFINE_FUNC(__nss_passwd_lookup2) \
DEFINE_FUNC(__nss_services_lookup2) \
DEFINE_FUNC(ntohl) \
DEFINE_FUNC(ntohs) \
DEFINE_FUNC(ntp_adjtime) \
DEFINE_FUNC(ntp_gettime) \
DEFINE_FUNC(ntp_gettimex) \
DEFINE_FUNC(_obstack_allocated_p) \
DEFINE_FUNC(_obstack_begin) \
DEFINE_FUNC(_obstack_begin_1) \
DEFINE_FUNC(_obstack_free) \
DEFINE_FUNC(obstack_free) \
DEFINE_FUNC(_obstack_memory_used) \
DEFINE_FUNC(_obstack_newchunk) \
DEFINE_FUNC(obstack_printf) \
DEFINE_FUNC(__obstack_printf_chk) \
DEFINE_FUNC(obstack_vprintf) \
DEFINE_FUNC(__obstack_vprintf_chk) \
DEFINE_FUNC(on_exit) \
DEFINE_FUNC(open) \
DEFINE_FUNC(__open) \
DEFINE_FUNC(__open_2) \
DEFINE_FUNC(open64) \
DEFINE_FUNC(__open64) \
DEFINE_FUNC(__open64_2) \
DEFINE_FUNC(openat) \
DEFINE_FUNC(__openat_2) \
DEFINE_FUNC(openat64) \
DEFINE_FUNC(__openat64_2) \
DEFINE_FUNC(open_by_handle_at) \
DEFINE_FUNC(__open_catalog) \
DEFINE_FUNC(opendir) \
DEFINE_FUNC(openlog) \
DEFINE_FUNC(open_memstream) \
DEFINE_FUNC(__open_nocancel) \
DEFINE_FUNC(open_wmemstream) \
DEFINE_FUNC(__overflow) \
DEFINE_FUNC(parse_printf_format) \
DEFINE_FUNC(passwd2des) \
DEFINE_FUNC(pathconf) \
DEFINE_FUNC(pause) \
DEFINE_FUNC(pclose) \
DEFINE_FUNC(perror) \
DEFINE_FUNC(personality) \
DEFINE_FUNC(pipe) \
DEFINE_FUNC(__pipe) \
DEFINE_FUNC(pipe2) \
DEFINE_FUNC(pivot_root) \
DEFINE_FUNC(pkey_alloc) \
DEFINE_FUNC(pkey_free) \
DEFINE_FUNC(pkey_get) \
DEFINE_FUNC(pkey_mprotect) \
DEFINE_FUNC(pkey_set) \
DEFINE_FUNC(pmap_getmaps) \
DEFINE_FUNC(pmap_getport) \
DEFINE_FUNC(pmap_rmtcall) \
DEFINE_FUNC(pmap_set) \
DEFINE_FUNC(pmap_unset) \
DEFINE_FUNC(poll) \
DEFINE_FUNC(__poll) \
DEFINE_FUNC(__poll_chk) \
DEFINE_FUNC(popen) \
DEFINE_FUNC(posix_fadvise) \
DEFINE_FUNC(posix_fadvise64) \
DEFINE_FUNC(posix_fallocate) \
DEFINE_FUNC(posix_fallocate64) \
DEFINE_FUNC(__posix_getopt) \
DEFINE_FUNC(posix_madvise) \
DEFINE_FUNC(posix_memalign) \
DEFINE_FUNC(posix_openpt) \
DEFINE_FUNC(posix_spawn) \
DEFINE_FUNC(posix_spawnattr_destroy) \
DEFINE_FUNC(posix_spawnattr_getflags) \
DEFINE_FUNC(posix_spawnattr_getpgroup) \
DEFINE_FUNC(posix_spawnattr_getschedp) \
DEFINE_FUNC(posix_spawnattr_getsigdef) \
DEFINE_FUNC(posix_spawnattr_getsigmas) \
DEFINE_FUNC(posix_spawnattr_init) \
DEFINE_FUNC(posix_spawnattr_setflags) \
DEFINE_FUNC(posix_spawnattr_setpgroup) \
DEFINE_FUNC(posix_spawnattr_setschedp) \
DEFINE_FUNC(posix_spawnattr_setsigdef) \
DEFINE_FUNC(posix_spawnattr_setsigmas) \
DEFINE_FUNC(posix_spawn_file_actions_) \
DEFINE_FUNC(posix_spawnp) \
DEFINE_FUNC(ppoll) \
DEFINE_FUNC(__ppoll_chk) \
DEFINE_FUNC(prctl) \
DEFINE_FUNC(pread) \
DEFINE_FUNC(pread64) \
DEFINE_FUNC(__pread64) \
DEFINE_FUNC(__pread64_chk) \
DEFINE_FUNC(__pread_chk) \
DEFINE_FUNC(preadv) \
DEFINE_FUNC(preadv2) \
DEFINE_FUNC(preadv64) \
DEFINE_FUNC(preadv64v2) \
/* DEFINE_FUNC(printf) */ \
DEFINE_FUNC(__printf_chk) \
DEFINE_FUNC(__printf_fp) \
DEFINE_FUNC(printf_size) \
DEFINE_FUNC(printf_size_info) \
DEFINE_FUNC(prlimit) \
DEFINE_FUNC(prlimit64) \
DEFINE_FUNC(process_vm_readv) \
DEFINE_FUNC(process_vm_writev) \
DEFINE_FUNC(profil) \
DEFINE_FUNC(__profile_frequency) \
DEFINE_FUNC(pselect) \
DEFINE_FUNC(psiginfo) \
DEFINE_FUNC(psignal) \
DEFINE_FUNC(pthread_attr_destroy) \
DEFINE_FUNC(pthread_attr_getdetachsta) \
DEFINE_FUNC(pthread_attr_getinheritsc) \
DEFINE_FUNC(pthread_attr_getschedpara) \
DEFINE_FUNC(pthread_attr_getschedpoli) \
DEFINE_FUNC(pthread_attr_getscope) \
DEFINE_FUNC(pthread_attr_init) \
DEFINE_FUNC(pthread_attr_setdetachsta) \
DEFINE_FUNC(pthread_attr_setinheritsc) \
DEFINE_FUNC(pthread_attr_setschedpara) \
DEFINE_FUNC(pthread_attr_setschedpoli) \
DEFINE_FUNC(pthread_attr_setscope) \
DEFINE_FUNC(pthread_condattr_destroy) \
DEFINE_FUNC(pthread_condattr_init) \
DEFINE_FUNC(pthread_cond_broadcast) \
DEFINE_FUNC(pthread_cond_destroy) \
DEFINE_FUNC(pthread_cond_init) \
DEFINE_FUNC(pthread_cond_signal) \
DEFINE_FUNC(pthread_cond_timedwait) \
DEFINE_FUNC(pthread_cond_wait) \
DEFINE_FUNC(pthread_equal) \
DEFINE_FUNC(pthread_exit) \
DEFINE_FUNC(pthread_getschedparam) \
DEFINE_FUNC(pthread_mutex_destroy) \
DEFINE_FUNC(pthread_mutex_init) \
DEFINE_FUNC(pthread_mutex_lock) \
DEFINE_FUNC(pthread_mutex_unlock) \
DEFINE_FUNC(pthread_self) \
DEFINE_FUNC(pthread_setcancelstate) \
DEFINE_FUNC(pthread_setcanceltype) \
DEFINE_FUNC(pthread_setschedparam) \
DEFINE_FUNC(ptrace) \
DEFINE_FUNC(ptsname) \
DEFINE_FUNC(ptsname_r) \
DEFINE_FUNC(__ptsname_r_chk) \
DEFINE_FUNC(putc) \
DEFINE_FUNC(putchar) \
DEFINE_FUNC(putchar_unlocked) \
DEFINE_FUNC(putc_unlocked) \
DEFINE_FUNC(putenv) \
DEFINE_FUNC(putgrent) \
DEFINE_FUNC(putmsg) \
DEFINE_FUNC(putpmsg) \
DEFINE_FUNC(putpwent) \
DEFINE_FUNC(puts) \
DEFINE_FUNC(putsgent) \
DEFINE_FUNC(putspent) \
DEFINE_FUNC(pututline) \
DEFINE_FUNC(pututxline) \
DEFINE_FUNC(putw) \
DEFINE_FUNC(putwc) \
DEFINE_FUNC(putwchar) \
DEFINE_FUNC(putwchar_unlocked) \
DEFINE_FUNC(putwc_unlocked) \
DEFINE_FUNC(pvalloc) \
DEFINE_FUNC(pwrite) \
DEFINE_FUNC(pwrite64) \
DEFINE_FUNC(__pwrite64) \
DEFINE_FUNC(pwritev) \
DEFINE_FUNC(pwritev2) \
DEFINE_FUNC(pwritev64) \
DEFINE_FUNC(pwritev64v2) \
DEFINE_FUNC(qecvt) \
DEFINE_FUNC(qecvt_r) \
DEFINE_FUNC(qfcvt) \
DEFINE_FUNC(qfcvt_r) \
DEFINE_FUNC(qgcvt) \
DEFINE_FUNC(qsort) \
DEFINE_FUNC(qsort_r) \
DEFINE_FUNC(query_module) \
DEFINE_FUNC(quick_exit) \
DEFINE_FUNC(quotactl) \
DEFINE_FUNC(raise) \
DEFINE_FUNC(rand) \
DEFINE_FUNC(random) \
DEFINE_FUNC(random_r) \
DEFINE_FUNC(rand_r) \
DEFINE_FUNC(rawmemchr) \
DEFINE_FUNC(__rawmemchr) \
DEFINE_FUNC(rcmd) \
DEFINE_FUNC(rcmd_af) \
DEFINE_FUNC(read) \
DEFINE_FUNC(__read) \
DEFINE_FUNC(readahead) \
DEFINE_FUNC(__read_chk) \
DEFINE_FUNC(readdir) \
DEFINE_FUNC(readdir64) \
DEFINE_FUNC(readdir64_r) \
DEFINE_FUNC(readdir_r) \
DEFINE_FUNC(readlink) \
DEFINE_FUNC(readlinkat) \
DEFINE_FUNC(__readlinkat_chk) \
DEFINE_FUNC(__readlink_chk) \
DEFINE_FUNC(__read_nocancel) \
DEFINE_FUNC(readv) \
DEFINE_FUNC(realloc) \
DEFINE_FUNC(reallocarray) \
DEFINE_FUNC(realpath) \
DEFINE_FUNC(__realpath_chk) \
DEFINE_FUNC(reboot) \
DEFINE_FUNC(re_comp) \
DEFINE_FUNC(re_compile_fastmap) \
DEFINE_FUNC(re_compile_pattern) \
DEFINE_FUNC(recv) \
DEFINE_FUNC(__recv) \
DEFINE_FUNC(__recv_chk) \
DEFINE_FUNC(recvfrom) \
DEFINE_FUNC(__recvfrom_chk) \
DEFINE_FUNC(recvmmsg) \
DEFINE_FUNC(recvmsg) \
DEFINE_FUNC(re_exec) \
DEFINE_FUNC(regcomp) \
DEFINE_FUNC(regerror) \
DEFINE_FUNC(regexec) \
DEFINE_FUNC(regfree) \
DEFINE_FUNC(__register_atfork) \
DEFINE_FUNC(__register_frame) \
DEFINE_FUNC(__register_frame_info) \
DEFINE_FUNC(__register_frame_info_bas) \
DEFINE_FUNC(__register_frame_info_tab) \
DEFINE_FUNC(__register_frame_table) \
DEFINE_FUNC(register_printf_function) \
DEFINE_FUNC(register_printf_modifier) \
DEFINE_FUNC(register_printf_specifier) \
DEFINE_FUNC(register_printf_type) \
DEFINE_FUNC(registerrpc) \
DEFINE_FUNC(remap_file_pages) \
DEFINE_FUNC(re_match) \
DEFINE_FUNC(re_match_2) \
DEFINE_FUNC(remove) \
DEFINE_FUNC(removexattr) \
DEFINE_FUNC(remque) \
DEFINE_FUNC(rename) \
DEFINE_FUNC(renameat) \
DEFINE_FUNC(re_search) \
DEFINE_FUNC(re_search_2) \
DEFINE_FUNC(re_set_registers) \
DEFINE_FUNC(re_set_syntax) \
DEFINE_FUNC(__res_iclose) \
DEFINE_FUNC(__res_init) \
DEFINE_FUNC(res_init) \
DEFINE_FUNC(__res_nclose) \
DEFINE_FUNC(__res_ninit) \
DEFINE_FUNC(__resolv_context_get) \
DEFINE_FUNC(__resolv_context_get_over) \
DEFINE_FUNC(__resolv_context_get_prei) \
DEFINE_FUNC(__resolv_context_put) \
DEFINE_FUNC(__res_randomid) \
DEFINE_FUNC(__res_state) \
DEFINE_FUNC(revoke) \
DEFINE_FUNC(rewind) \
DEFINE_FUNC(rewinddir) \
DEFINE_FUNC(rexec) \
DEFINE_FUNC(rexec_af) \
DEFINE_FUNC(rindex) \
DEFINE_FUNC(rmdir) \
DEFINE_FUNC(_rpc_dtablesize) \
DEFINE_FUNC(__rpc_thread_createerr) \
DEFINE_FUNC(__rpc_thread_svc_fdset) \
DEFINE_FUNC(__rpc_thread_svc_max_poll) \
DEFINE_FUNC(__rpc_thread_svc_pollfd) \
DEFINE_FUNC(rpmatch) \
DEFINE_FUNC(rresvport) \
DEFINE_FUNC(rresvport_af) \
DEFINE_FUNC(rtime) \
DEFINE_FUNC(ruserok) \
DEFINE_FUNC(ruserok_af) \
DEFINE_FUNC(ruserpass) \
DEFINE_FUNC(sbrk) \
DEFINE_FUNC(__sbrk) \
DEFINE_FUNC(scalbln) \
DEFINE_FUNC(scalblnf) \
DEFINE_FUNC(scalblnl) \
DEFINE_FUNC(scalbn) \
DEFINE_FUNC(scalbnf) \
DEFINE_FUNC(scalbnl) \
DEFINE_FUNC(scandir) \
DEFINE_FUNC(scandir64) \
DEFINE_FUNC(scandirat) \
DEFINE_FUNC(scandirat64) \
DEFINE_FUNC(scanf) \
DEFINE_FUNC(__sched_cpualloc) \
DEFINE_FUNC(__sched_cpucount) \
DEFINE_FUNC(__sched_cpufree) \
DEFINE_FUNC(sched_getaffinity) \
DEFINE_FUNC(sched_getcpu) \
DEFINE_FUNC(__sched_getparam) \
DEFINE_FUNC(sched_getparam) \
DEFINE_FUNC(__sched_get_priority_max) \
DEFINE_FUNC(sched_get_priority_max) \
DEFINE_FUNC(__sched_get_priority_min) \
DEFINE_FUNC(sched_get_priority_min) \
DEFINE_FUNC(__sched_getscheduler) \
DEFINE_FUNC(sched_getscheduler) \
DEFINE_FUNC(sched_rr_get_interval) \
DEFINE_FUNC(sched_setaffinity) \
DEFINE_FUNC(sched_setparam) \
DEFINE_FUNC(__sched_setscheduler) \
DEFINE_FUNC(sched_setscheduler) \
DEFINE_FUNC(__sched_yield) \
DEFINE_FUNC(sched_yield) \
DEFINE_FUNC(__secure_getenv) \
DEFINE_FUNC(secure_getenv) \
DEFINE_FUNC(seed48) \
DEFINE_FUNC(seed48_r) \
DEFINE_FUNC(seekdir) \
DEFINE_FUNC(select) \
DEFINE_FUNC(__select) \
DEFINE_FUNC(semctl) \
DEFINE_FUNC(semget) \
DEFINE_FUNC(semop) \
DEFINE_FUNC(semtimedop) \
DEFINE_FUNC(send) \
DEFINE_FUNC(__send) \
DEFINE_FUNC(sendfile) \
DEFINE_FUNC(sendfile64) \
DEFINE_FUNC(sendmmsg) \
DEFINE_FUNC(__sendmmsg) \
DEFINE_FUNC(sendmsg) \
DEFINE_FUNC(sendto) \
DEFINE_FUNC(setaliasent) \
DEFINE_FUNC(setbuf) \
DEFINE_FUNC(setbuffer) \
DEFINE_FUNC(setcontext) \
DEFINE_FUNC(setdomainname) \
DEFINE_FUNC(setegid) \
DEFINE_FUNC(setenv) \
DEFINE_FUNC(_seterr_reply) \
DEFINE_FUNC(seteuid) \
DEFINE_FUNC(setfsent) \
DEFINE_FUNC(setfsgid) \
DEFINE_FUNC(setfsuid) \
DEFINE_FUNC(setgid) \
DEFINE_FUNC(setgrent) \
DEFINE_FUNC(setgroups) \
DEFINE_FUNC(sethostent) \
DEFINE_FUNC(sethostid) \
DEFINE_FUNC(sethostname) \
DEFINE_FUNC(setipv4sourcefilter) \
DEFINE_FUNC(setitimer) \
DEFINE_FUNC(setjmp) \
DEFINE_FUNC(_setjmp) \
DEFINE_FUNC(setlinebuf) \
DEFINE_FUNC(setlocale) \
DEFINE_FUNC(setlogin) \
DEFINE_FUNC(setlogmask) \
DEFINE_FUNC(setmntent) \
DEFINE_FUNC(__setmntent) \
DEFINE_FUNC(setnetent) \
DEFINE_FUNC(setnetgrent) \
DEFINE_FUNC(setns) \
DEFINE_FUNC(setpgid) \
DEFINE_FUNC(__setpgid) \
DEFINE_FUNC(setpgrp) \
DEFINE_FUNC(setpriority) \
DEFINE_FUNC(setprotoent) \
DEFINE_FUNC(setpwent) \
DEFINE_FUNC(setregid) \
DEFINE_FUNC(setresgid) \
DEFINE_FUNC(setresuid) \
DEFINE_FUNC(setreuid) \
DEFINE_FUNC(setrlimit) \
DEFINE_FUNC(setrlimit64) \
DEFINE_FUNC(setrpcent) \
DEFINE_FUNC(setservent) \
DEFINE_FUNC(setsgent) \
DEFINE_FUNC(setsid) \
DEFINE_FUNC(setsockopt) \
DEFINE_FUNC(setsourcefilter) \
DEFINE_FUNC(setspent) \
DEFINE_FUNC(setstate) \
DEFINE_FUNC(setstate_r) \
DEFINE_FUNC(settimeofday) \
DEFINE_FUNC(setttyent) \
DEFINE_FUNC(setuid) \
DEFINE_FUNC(setusershell) \
DEFINE_FUNC(setutent) \
DEFINE_FUNC(setutxent) \
DEFINE_FUNC(setvbuf) \
DEFINE_FUNC(setxattr) \
DEFINE_FUNC(sgetsgent) \
DEFINE_FUNC(sgetsgent_r) \
DEFINE_FUNC(sgetspent) \
DEFINE_FUNC(sgetspent_r) \
DEFINE_FUNC(shmat) \
DEFINE_FUNC(shmctl) \
DEFINE_FUNC(shmdt) \
DEFINE_FUNC(shmget) \
DEFINE_FUNC(shutdown) \
DEFINE_FUNC(sigaction) \
DEFINE_FUNC(__sigaction) \
DEFINE_FUNC(sigaddset) \
DEFINE_FUNC(__sigaddset) \
DEFINE_FUNC(sigaltstack) \
DEFINE_FUNC(sigandset) \
DEFINE_FUNC(sigblock) \
DEFINE_FUNC(sigdelset) \
DEFINE_FUNC(__sigdelset) \
DEFINE_FUNC(sigemptyset) \
DEFINE_FUNC(sigfillset) \
DEFINE_FUNC(siggetmask) \
DEFINE_FUNC(sighold) \
DEFINE_FUNC(sigignore) \
DEFINE_FUNC(siginterrupt) \
DEFINE_FUNC(sigisemptyset) \
DEFINE_FUNC(sigismember) \
DEFINE_FUNC(__sigismember) \
DEFINE_FUNC(siglongjmp) \
DEFINE_FUNC(signal) \
DEFINE_FUNC(signalfd) \
DEFINE_FUNC(__signbit) \
DEFINE_FUNC(__signbitf) \
DEFINE_FUNC(__signbitl) \
DEFINE_FUNC(sigorset) \
DEFINE_FUNC(sigpause) \
DEFINE_FUNC(__sigpause) \
DEFINE_FUNC(sigpending) \
DEFINE_FUNC(sigprocmask) \
DEFINE_FUNC(sigqueue) \
DEFINE_FUNC(sigrelse) \
DEFINE_FUNC(sigreturn) \
DEFINE_FUNC(sigset) \
DEFINE_FUNC(__sigsetjmp) \
DEFINE_FUNC(sigsetmask) \
DEFINE_FUNC(sigstack) \
DEFINE_FUNC(sigsuspend) \
DEFINE_FUNC(__sigsuspend) \
DEFINE_FUNC(sigtimedwait) \
DEFINE_FUNC(__sigtimedwait) \
DEFINE_FUNC(sigvec) \
DEFINE_FUNC(sigwait) \
DEFINE_FUNC(sigwaitinfo) \
DEFINE_FUNC(sleep) \
DEFINE_FUNC(snprintf) \
DEFINE_FUNC(__snprintf) \
DEFINE_FUNC(__snprintf_chk) \
DEFINE_FUNC(sockatmark) \
DEFINE_FUNC(socket) \
DEFINE_FUNC(__socket) \
DEFINE_FUNC(socketpair) \
DEFINE_FUNC(splice) \
DEFINE_FUNC(sprintf) \
DEFINE_FUNC(__sprintf_chk) \
DEFINE_FUNC(sprofil) \
DEFINE_FUNC(srand) \
DEFINE_FUNC(srand48) \
DEFINE_FUNC(srand48_r) \
DEFINE_FUNC(srandom) \
DEFINE_FUNC(srandom_r) \
DEFINE_FUNC(sscanf) \
DEFINE_FUNC(ssignal) \
DEFINE_FUNC(sstk) \
DEFINE_FUNC(__stack_chk_fail) \
DEFINE_FUNC(statfs) \
DEFINE_FUNC(__statfs) \
DEFINE_FUNC(statfs64) \
DEFINE_FUNC(statvfs) \
DEFINE_FUNC(statvfs64) \
DEFINE_FUNC(step) \
DEFINE_FUNC(stime) \
DEFINE_FUNC(stpcpy) \
DEFINE_FUNC(__stpcpy) \
DEFINE_FUNC(__stpcpy_chk) \
DEFINE_FUNC(__stpcpy_g) \
DEFINE_FUNC(__stpcpy_small) \
DEFINE_FUNC(stpncpy) \
DEFINE_FUNC(__stpncpy) \
DEFINE_FUNC(__stpncpy_chk) \
DEFINE_FUNC(strcasecmp) \
DEFINE_FUNC(__strcasecmp) \
DEFINE_FUNC(__strcasecmp_l) \
DEFINE_FUNC(strcasecmp_l) \
DEFINE_FUNC(strcasestr) \
DEFINE_FUNC(__strcasestr) \
DEFINE_FUNC(strcat) \
DEFINE_FUNC(__strcat_c) \
DEFINE_FUNC(__strcat_chk) \
DEFINE_FUNC(__strcat_g) \
DEFINE_FUNC(strchr) \
DEFINE_FUNC(__strchr_c) \
DEFINE_FUNC(__strchr_g) \
DEFINE_FUNC(strchrnul) \
DEFINE_FUNC(__strchrnul_c) \
DEFINE_FUNC(__strchrnul_g) \
DEFINE_FUNC(strcmp) \
DEFINE_FUNC(__strcmp_gg) \
DEFINE_FUNC(strcoll) \
DEFINE_FUNC(__strcoll_l) \
DEFINE_FUNC(strcoll_l) \
DEFINE_FUNC(strcpy) \
DEFINE_FUNC(__strcpy_chk) \
DEFINE_FUNC(__strcpy_g) \
DEFINE_FUNC(__strcpy_small) \
DEFINE_FUNC(strcspn) \
DEFINE_FUNC(__strcspn_c1) \
DEFINE_FUNC(__strcspn_c2) \
DEFINE_FUNC(__strcspn_c3) \
DEFINE_FUNC(__strcspn_cg) \
DEFINE_FUNC(__strcspn_g) \
DEFINE_FUNC(strdup) \
DEFINE_FUNC(__strdup) \
DEFINE_FUNC(strerror) \
DEFINE_FUNC(strerror_l) \
DEFINE_FUNC(__strerror_r) \
DEFINE_FUNC(strerror_r) \
DEFINE_FUNC(strfmon) \
DEFINE_FUNC(__strfmon_l) \
DEFINE_FUNC(strfmon_l) \
DEFINE_FUNC(strfromd) \
DEFINE_FUNC(strfromf) \
DEFINE_FUNC(strfromf128) \
DEFINE_FUNC(strfromf32) \
DEFINE_FUNC(strfromf32x) \
DEFINE_FUNC(strfromf64) \
DEFINE_FUNC(strfromf64x) \
DEFINE_FUNC(strfroml) \
DEFINE_FUNC(strfry) \
DEFINE_FUNC(strftime) \
DEFINE_FUNC(__strftime_l) \
DEFINE_FUNC(strftime_l) \
DEFINE_FUNC(strlen) \
DEFINE_FUNC(__strlen_g) \
DEFINE_FUNC(strncasecmp) \
DEFINE_FUNC(__strncasecmp_l) \
DEFINE_FUNC(strncasecmp_l) \
DEFINE_FUNC(strncat) \
DEFINE_FUNC(__strncat_chk) \
DEFINE_FUNC(__strncat_g) \
DEFINE_FUNC(strncmp) \
DEFINE_FUNC(__strncmp_g) \
DEFINE_FUNC(strncpy) \
DEFINE_FUNC(__strncpy_by2) \
DEFINE_FUNC(__strncpy_by4) \
DEFINE_FUNC(__strncpy_byn) \
DEFINE_FUNC(__strncpy_chk) \
DEFINE_FUNC(__strncpy_gg) \
DEFINE_FUNC(strndup) \
DEFINE_FUNC(__strndup) \
DEFINE_FUNC(strnlen) \
DEFINE_FUNC(strpbrk) \
DEFINE_FUNC(__strpbrk_c2) \
DEFINE_FUNC(__strpbrk_c3) \
DEFINE_FUNC(__strpbrk_cg) \
DEFINE_FUNC(__strpbrk_g) \
DEFINE_FUNC(strptime) \
DEFINE_FUNC(strptime_l) \
DEFINE_FUNC(strrchr) \
DEFINE_FUNC(__strrchr_c) \
DEFINE_FUNC(__strrchr_g) \
DEFINE_FUNC(strsep) \
DEFINE_FUNC(__strsep_1c) \
DEFINE_FUNC(__strsep_2c) \
DEFINE_FUNC(__strsep_3c) \
DEFINE_FUNC(__strsep_g) \
DEFINE_FUNC(strsignal) \
DEFINE_FUNC(strspn) \
DEFINE_FUNC(__strspn_c1) \
DEFINE_FUNC(__strspn_c2) \
DEFINE_FUNC(__strspn_c3) \
DEFINE_FUNC(__strspn_cg) \
DEFINE_FUNC(__strspn_g) \
DEFINE_FUNC(strstr) \
DEFINE_FUNC(__strstr_cg) \
DEFINE_FUNC(__strstr_g) \
DEFINE_FUNC(strtod) \
DEFINE_FUNC(__strtod_internal) \
DEFINE_FUNC(__strtod_l) \
DEFINE_FUNC(strtod_l) \
DEFINE_FUNC(__strtod_nan) \
DEFINE_FUNC(strtof) \
DEFINE_FUNC(strtof128) \
DEFINE_FUNC(__strtof128_internal) \
DEFINE_FUNC(strtof128_l) \
DEFINE_FUNC(__strtof128_nan) \
DEFINE_FUNC(strtof32) \
DEFINE_FUNC(strtof32_l) \
DEFINE_FUNC(strtof32x) \
DEFINE_FUNC(strtof32x_l) \
DEFINE_FUNC(strtof64) \
DEFINE_FUNC(strtof64_l) \
DEFINE_FUNC(strtof64x) \
DEFINE_FUNC(strtof64x_l) \
DEFINE_FUNC(__strtof_internal) \
DEFINE_FUNC(__strtof_l) \
DEFINE_FUNC(strtof_l) \
DEFINE_FUNC(__strtof_nan) \
DEFINE_FUNC(strtoimax) \
DEFINE_FUNC(strtok) \
DEFINE_FUNC(__strtok_r) \
DEFINE_FUNC(strtok_r) \
DEFINE_FUNC(__strtok_r_1c) \
DEFINE_FUNC(strtol) \
DEFINE_FUNC(strtold) \
DEFINE_FUNC(__strtold_internal) \
DEFINE_FUNC(__strtold_l) \
DEFINE_FUNC(strtold_l) \
DEFINE_FUNC(__strtold_nan) \
DEFINE_FUNC(__strtol_internal) \
DEFINE_FUNC(strtoll) \
DEFINE_FUNC(__strtol_l) \
DEFINE_FUNC(strtol_l) \
DEFINE_FUNC(__strtoll_internal) \
DEFINE_FUNC(__strtoll_l) \
DEFINE_FUNC(strtoll_l) \
DEFINE_FUNC(strtoq) \
DEFINE_FUNC(__strtoq_internal) \
DEFINE_FUNC(strtoul) \
DEFINE_FUNC(__strtoul_internal) \
DEFINE_FUNC(strtoull) \
DEFINE_FUNC(__strtoul_l) \
DEFINE_FUNC(strtoul_l) \
DEFINE_FUNC(__strtoull_internal) \
DEFINE_FUNC(__strtoull_l) \
DEFINE_FUNC(strtoull_l) \
DEFINE_FUNC(strtoumax) \
DEFINE_FUNC(strtouq) \
DEFINE_FUNC(__strtouq_internal) \
DEFINE_FUNC(strverscmp) \
DEFINE_FUNC(__strverscmp) \
DEFINE_FUNC(strxfrm) \
DEFINE_FUNC(__strxfrm_l) \
DEFINE_FUNC(strxfrm_l) \
DEFINE_FUNC(stty) \
DEFINE_FUNC(svcerr_auth) \
DEFINE_FUNC(svcerr_decode) \
DEFINE_FUNC(svcerr_noproc) \
DEFINE_FUNC(svcerr_noprog) \
DEFINE_FUNC(svcerr_progvers) \
DEFINE_FUNC(svcerr_systemerr) \
DEFINE_FUNC(svcerr_weakauth) \
DEFINE_FUNC(svc_exit) \
DEFINE_FUNC(svcfd_create) \
DEFINE_FUNC(svc_getreq) \
DEFINE_FUNC(svc_getreq_common) \
DEFINE_FUNC(svc_getreq_poll) \
DEFINE_FUNC(svc_getreqset) \
DEFINE_FUNC(svcraw_create) \
DEFINE_FUNC(svc_register) \
DEFINE_FUNC(svc_run) \
DEFINE_FUNC(svc_sendreply) \
DEFINE_FUNC(svctcp_create) \
DEFINE_FUNC(svcudp_bufcreate) \
DEFINE_FUNC(svcudp_create) \
DEFINE_FUNC(svcudp_enablecache) \
DEFINE_FUNC(svcunix_create) \
DEFINE_FUNC(svcunixfd_create) \
DEFINE_FUNC(svc_unregister) \
DEFINE_FUNC(swab) \
DEFINE_FUNC(swapcontext) \
DEFINE_FUNC(swapoff) \
DEFINE_FUNC(swapon) \
DEFINE_FUNC(swprintf) \
DEFINE_FUNC(__swprintf_chk) \
DEFINE_FUNC(swscanf) \
DEFINE_FUNC(symlink) \
DEFINE_FUNC(symlinkat) \
DEFINE_FUNC(sync) \
DEFINE_FUNC(sync_file_range) \
DEFINE_FUNC(syncfs) \
DEFINE_FUNC(syscall) \
DEFINE_FUNC(sysconf) \
DEFINE_FUNC(__sysconf) \
DEFINE_FUNC(sysctl) \
DEFINE_FUNC(__sysctl) \
DEFINE_FUNC(sysinfo) \
DEFINE_FUNC(syslog) \
DEFINE_FUNC(__syslog_chk) \
DEFINE_FUNC(system) \
DEFINE_FUNC(__sysv_signal) \
DEFINE_FUNC(sysv_signal) \
DEFINE_FUNC(tcdrain) \
DEFINE_FUNC(tcflow) \
DEFINE_FUNC(tcflush) \
DEFINE_FUNC(tcgetattr) \
DEFINE_FUNC(tcgetpgrp) \
DEFINE_FUNC(tcgetsid) \
DEFINE_FUNC(tcsendbreak) \
DEFINE_FUNC(tcsetattr) \
DEFINE_FUNC(tcsetpgrp) \
DEFINE_FUNC(tdelete) \
DEFINE_FUNC(__tdelete) \
DEFINE_FUNC(tdestroy) \
DEFINE_FUNC(tee) \
DEFINE_FUNC(telldir) \
DEFINE_FUNC(tempnam) \
DEFINE_FUNC(textdomain) \
DEFINE_FUNC(tfind) \
DEFINE_FUNC(__tfind) \
DEFINE_FUNC(time) \
DEFINE_FUNC(timegm) \
DEFINE_FUNC(timelocal) \
DEFINE_FUNC(timerfd_create) \
DEFINE_FUNC(timerfd_gettime) \
DEFINE_FUNC(timerfd_settime) \
DEFINE_FUNC(times) \
DEFINE_FUNC(timespec_get) \
DEFINE_FUNC(tmpfile) \
DEFINE_FUNC(tmpfile64) \
DEFINE_FUNC(tmpnam) \
DEFINE_FUNC(tmpnam_r) \
DEFINE_FUNC(toascii) \
DEFINE_FUNC(__toascii_l) \
DEFINE_FUNC(tolower) \
DEFINE_FUNC(_tolower) \
DEFINE_FUNC(__tolower_l) \
DEFINE_FUNC(tolower_l) \
DEFINE_FUNC(toupper) \
DEFINE_FUNC(_toupper) \
DEFINE_FUNC(__toupper_l) \
DEFINE_FUNC(toupper_l) \
DEFINE_FUNC(towctrans) \
DEFINE_FUNC(__towctrans) \
DEFINE_FUNC(__towctrans_l) \
DEFINE_FUNC(towctrans_l) \
DEFINE_FUNC(towlower) \
DEFINE_FUNC(__towlower_l) \
DEFINE_FUNC(towlower_l) \
DEFINE_FUNC(towupper) \
DEFINE_FUNC(__towupper_l) \
DEFINE_FUNC(towupper_l) \
DEFINE_FUNC(tr_break) \
DEFINE_FUNC(truncate) \
DEFINE_FUNC(truncate64) \
DEFINE_FUNC(tsearch) \
DEFINE_FUNC(__tsearch) \
DEFINE_FUNC(ttyname) \
DEFINE_FUNC(ttyname_r) \
DEFINE_FUNC(__ttyname_r_chk) \
DEFINE_FUNC(ttyslot) \
DEFINE_FUNC(twalk) \
DEFINE_FUNC(__twalk) \
DEFINE_FUNC(tzset) \
DEFINE_FUNC(ualarm) \
DEFINE_FUNC(__udivdi3) \
DEFINE_FUNC(__uflow) \
DEFINE_FUNC(ulckpwdf) \
DEFINE_FUNC(ulimit) \
DEFINE_FUNC(umask) \
DEFINE_FUNC(__umoddi3) \
DEFINE_FUNC(umount) \
DEFINE_FUNC(umount2) \
DEFINE_FUNC(uname) \
DEFINE_FUNC(__uname) \
DEFINE_FUNC(__underflow) \
DEFINE_FUNC(ungetc) \
DEFINE_FUNC(ungetwc) \
DEFINE_FUNC(unlink) \
DEFINE_FUNC(unlinkat) \
DEFINE_FUNC(unlockpt) \
DEFINE_FUNC(unsetenv) \
DEFINE_FUNC(unshare) \
DEFINE_FUNC(_Unwind_Find_FDE) \
DEFINE_FUNC(updwtmp) \
DEFINE_FUNC(updwtmpx) \
DEFINE_FUNC(uselib) \
DEFINE_FUNC(uselocale) \
DEFINE_FUNC(__uselocale) \
DEFINE_FUNC(user2netname) \
DEFINE_FUNC(usleep) \
DEFINE_FUNC(ustat) \
DEFINE_FUNC(utime) \
DEFINE_FUNC(utimensat) \
DEFINE_FUNC(utimes) \
DEFINE_FUNC(utmpname) \
DEFINE_FUNC(utmpxname) \
DEFINE_FUNC(valloc) \
DEFINE_FUNC(vasprintf) \
DEFINE_FUNC(__vasprintf_chk) \
DEFINE_FUNC(vdprintf) \
DEFINE_FUNC(__vdprintf_chk) \
DEFINE_FUNC(verr) \
DEFINE_FUNC(verrx) \
DEFINE_FUNC(versionsort) \
DEFINE_FUNC(versionsort64) \
DEFINE_FUNC(vfork) \
DEFINE_FUNC(__vfork) \
DEFINE_FUNC(vfprintf) \
DEFINE_FUNC(__vfprintf_chk) \
DEFINE_FUNC(vfscanf) \
DEFINE_FUNC(__vfscanf) \
DEFINE_FUNC(vfwprintf) \
DEFINE_FUNC(__vfwprintf_chk) \
DEFINE_FUNC(vfwscanf) \
DEFINE_FUNC(vhangup) \
DEFINE_FUNC(vlimit) \
DEFINE_FUNC(vm86) \
DEFINE_FUNC(vmsplice) \
DEFINE_FUNC(vprintf) \
DEFINE_FUNC(__vprintf_chk) \
DEFINE_FUNC(vscanf) \
DEFINE_FUNC(vsnprintf) \
DEFINE_FUNC(__vsnprintf) \
DEFINE_FUNC(__vsnprintf_chk) \
DEFINE_FUNC(vsprintf) \
DEFINE_FUNC(__vsprintf_chk) \
DEFINE_FUNC(vsscanf) \
DEFINE_FUNC(__vsscanf) \
DEFINE_FUNC(vswprintf) \
DEFINE_FUNC(__vswprintf_chk) \
DEFINE_FUNC(vswscanf) \
DEFINE_FUNC(vsyslog) \
DEFINE_FUNC(__vsyslog_chk) \
DEFINE_FUNC(vtimes) \
DEFINE_FUNC(vwarn) \
DEFINE_FUNC(vwarnx) \
DEFINE_FUNC(vwprintf) \
DEFINE_FUNC(__vwprintf_chk) \
DEFINE_FUNC(vwscanf) \
DEFINE_FUNC(wait) \
DEFINE_FUNC(__wait) \
DEFINE_FUNC(wait3) \
DEFINE_FUNC(wait4) \
DEFINE_FUNC(waitid) \
DEFINE_FUNC(waitpid) \
DEFINE_FUNC(__waitpid) \
DEFINE_FUNC(warn) \
DEFINE_FUNC(warnx) \
DEFINE_FUNC(wcpcpy) \
DEFINE_FUNC(__wcpcpy_chk) \
DEFINE_FUNC(wcpncpy) \
DEFINE_FUNC(__wcpncpy_chk) \
DEFINE_FUNC(wcrtomb) \
DEFINE_FUNC(__wcrtomb_chk) \
DEFINE_FUNC(wcscasecmp) \
DEFINE_FUNC(__wcscasecmp_l) \
DEFINE_FUNC(wcscasecmp_l) \
DEFINE_FUNC(wcscat) \
DEFINE_FUNC(__wcscat_chk) \
DEFINE_FUNC(wcschr) \
DEFINE_FUNC(wcschrnul) \
DEFINE_FUNC(wcscmp) \
DEFINE_FUNC(wcscoll) \
DEFINE_FUNC(__wcscoll_l) \
DEFINE_FUNC(wcscoll_l) \
DEFINE_FUNC(wcscpy) \
DEFINE_FUNC(__wcscpy_chk) \
DEFINE_FUNC(wcscspn) \
DEFINE_FUNC(wcsdup) \
DEFINE_FUNC(wcsftime) \
DEFINE_FUNC(__wcsftime_l) \
DEFINE_FUNC(wcsftime_l) \
DEFINE_FUNC(wcslen) \
DEFINE_FUNC(wcsncasecmp) \
DEFINE_FUNC(__wcsncasecmp_l) \
DEFINE_FUNC(wcsncasecmp_l) \
DEFINE_FUNC(wcsncat) \
DEFINE_FUNC(__wcsncat_chk) \
DEFINE_FUNC(wcsncmp) \
DEFINE_FUNC(wcsncpy) \
DEFINE_FUNC(__wcsncpy_chk) \
DEFINE_FUNC(wcsnlen) \
DEFINE_FUNC(wcsnrtombs) \
DEFINE_FUNC(__wcsnrtombs_chk) \
DEFINE_FUNC(wcspbrk) \
DEFINE_FUNC(wcsrchr) \
DEFINE_FUNC(wcsrtombs) \
DEFINE_FUNC(__wcsrtombs_chk) \
DEFINE_FUNC(wcsspn) \
DEFINE_FUNC(wcsstr) \
DEFINE_FUNC(wcstod) \
DEFINE_FUNC(__wcstod_internal) \
DEFINE_FUNC(__wcstod_l) \
DEFINE_FUNC(wcstod_l) \
DEFINE_FUNC(wcstof) \
DEFINE_FUNC(wcstof128) \
DEFINE_FUNC(__wcstof128_internal) \
DEFINE_FUNC(wcstof128_l) \
DEFINE_FUNC(wcstof32) \
DEFINE_FUNC(wcstof32_l) \
DEFINE_FUNC(wcstof32x) \
DEFINE_FUNC(wcstof32x_l) \
DEFINE_FUNC(wcstof64) \
DEFINE_FUNC(wcstof64_l) \
DEFINE_FUNC(wcstof64x) \
DEFINE_FUNC(wcstof64x_l) \
DEFINE_FUNC(__wcstof_internal) \
DEFINE_FUNC(__wcstof_l) \
DEFINE_FUNC(wcstof_l) \
DEFINE_FUNC(wcstoimax) \
DEFINE_FUNC(wcstok) \
DEFINE_FUNC(wcstol) \
DEFINE_FUNC(wcstold) \
DEFINE_FUNC(__wcstold_internal) \
DEFINE_FUNC(__wcstold_l) \
DEFINE_FUNC(wcstold_l) \
DEFINE_FUNC(__wcstol_internal) \
DEFINE_FUNC(wcstoll) \
DEFINE_FUNC(__wcstol_l) \
DEFINE_FUNC(wcstol_l) \
DEFINE_FUNC(__wcstoll_internal) \
DEFINE_FUNC(__wcstoll_l) \
DEFINE_FUNC(wcstoll_l) \
DEFINE_FUNC(wcstombs) \
DEFINE_FUNC(__wcstombs_chk) \
DEFINE_FUNC(wcstoq) \
DEFINE_FUNC(wcstoul) \
DEFINE_FUNC(__wcstoul_internal) \
DEFINE_FUNC(wcstoull) \
DEFINE_FUNC(__wcstoul_l) \
DEFINE_FUNC(wcstoul_l) \
DEFINE_FUNC(__wcstoull_internal) \
DEFINE_FUNC(__wcstoull_l) \
DEFINE_FUNC(wcstoull_l) \
DEFINE_FUNC(wcstoumax) \
DEFINE_FUNC(wcstouq) \
DEFINE_FUNC(wcswcs) \
DEFINE_FUNC(wcswidth) \
DEFINE_FUNC(wcsxfrm) \
DEFINE_FUNC(__wcsxfrm_l) \
DEFINE_FUNC(wcsxfrm_l) \
DEFINE_FUNC(wctob) \
DEFINE_FUNC(wctomb) \
DEFINE_FUNC(__wctomb_chk) \
DEFINE_FUNC(wctrans) \
DEFINE_FUNC(__wctrans_l) \
DEFINE_FUNC(wctrans_l) \
DEFINE_FUNC(wctype) \
DEFINE_FUNC(__wctype_l) \
DEFINE_FUNC(wctype_l) \
DEFINE_FUNC(wcwidth) \
DEFINE_FUNC(wmemchr) \
DEFINE_FUNC(wmemcmp) \
DEFINE_FUNC(wmemcpy) \
DEFINE_FUNC(__wmemcpy_chk) \
DEFINE_FUNC(wmemmove) \
DEFINE_FUNC(__wmemmove_chk) \
DEFINE_FUNC(wmempcpy) \
DEFINE_FUNC(__wmempcpy_chk) \
DEFINE_FUNC(wmemset) \
DEFINE_FUNC(__wmemset_chk) \
DEFINE_FUNC(wordexp) \
DEFINE_FUNC(wordfree) \
DEFINE_FUNC(__woverflow) \
DEFINE_FUNC(wprintf) \
DEFINE_FUNC(__wprintf_chk) \
DEFINE_FUNC(write) \
DEFINE_FUNC(__write) \
DEFINE_FUNC(writev) \
DEFINE_FUNC(wscanf) \
DEFINE_FUNC(__wuflow) \
DEFINE_FUNC(__wunderflow) \
DEFINE_FUNC(xdecrypt) \
DEFINE_FUNC(xdr_accepted_reply) \
DEFINE_FUNC(xdr_array) \
DEFINE_FUNC(xdr_authdes_cred) \
DEFINE_FUNC(xdr_authdes_verf) \
DEFINE_FUNC(xdr_authunix_parms) \
DEFINE_FUNC(xdr_bool) \
DEFINE_FUNC(xdr_bytes) \
DEFINE_FUNC(xdr_callhdr) \
DEFINE_FUNC(xdr_callmsg) \
DEFINE_FUNC(xdr_char) \
DEFINE_FUNC(xdr_cryptkeyarg) \
DEFINE_FUNC(xdr_cryptkeyarg2) \
DEFINE_FUNC(xdr_cryptkeyres) \
DEFINE_FUNC(xdr_des_block) \
DEFINE_FUNC(xdr_double) \
DEFINE_FUNC(xdr_enum) \
DEFINE_FUNC(xdr_float) \
DEFINE_FUNC(xdr_free) \
DEFINE_FUNC(xdr_getcredres) \
DEFINE_FUNC(xdr_hyper) \
DEFINE_FUNC(xdr_int) \
DEFINE_FUNC(xdr_int16_t) \
DEFINE_FUNC(xdr_int32_t) \
DEFINE_FUNC(xdr_int64_t) \
DEFINE_FUNC(xdr_int8_t) \
DEFINE_FUNC(xdr_keybuf) \
DEFINE_FUNC(xdr_key_netstarg) \
DEFINE_FUNC(xdr_key_netstres) \
DEFINE_FUNC(xdr_keystatus) \
DEFINE_FUNC(xdr_long) \
DEFINE_FUNC(xdr_longlong_t) \
DEFINE_FUNC(xdrmem_create) \
DEFINE_FUNC(xdr_netnamestr) \
DEFINE_FUNC(xdr_netobj) \
DEFINE_FUNC(xdr_opaque) \
DEFINE_FUNC(xdr_opaque_auth) \
DEFINE_FUNC(xdr_pmap) \
DEFINE_FUNC(xdr_pmaplist) \
DEFINE_FUNC(xdr_pointer) \
DEFINE_FUNC(xdr_quad_t) \
DEFINE_FUNC(xdrrec_create) \
DEFINE_FUNC(xdrrec_endofrecord) \
DEFINE_FUNC(xdrrec_eof) \
DEFINE_FUNC(xdrrec_skiprecord) \
DEFINE_FUNC(xdr_reference) \
DEFINE_FUNC(xdr_rejected_reply) \
DEFINE_FUNC(xdr_replymsg) \
DEFINE_FUNC(xdr_rmtcall_args) \
DEFINE_FUNC(xdr_rmtcallres) \
DEFINE_FUNC(xdr_short) \
DEFINE_FUNC(xdr_sizeof) \
DEFINE_FUNC(xdrstdio_create) \
DEFINE_FUNC(xdr_string) \
DEFINE_FUNC(xdr_u_char) \
DEFINE_FUNC(xdr_u_hyper) \
DEFINE_FUNC(xdr_u_int) \
DEFINE_FUNC(xdr_uint16_t) \
DEFINE_FUNC(xdr_uint32_t) \
DEFINE_FUNC(xdr_uint64_t) \
DEFINE_FUNC(xdr_uint8_t) \
DEFINE_FUNC(xdr_u_long) \
DEFINE_FUNC(xdr_u_longlong_t) \
DEFINE_FUNC(xdr_union) \
DEFINE_FUNC(xdr_unixcred) \
DEFINE_FUNC(xdr_u_quad_t) \
DEFINE_FUNC(xdr_u_short) \
DEFINE_FUNC(xdr_vector) \
DEFINE_FUNC(xdr_void) \
DEFINE_FUNC(xdr_wrapstring) \
DEFINE_FUNC(xencrypt) \
DEFINE_FUNC(__xmknod) \
DEFINE_FUNC(__xmknodat) \
DEFINE_FUNC(__xpg_basename) \
DEFINE_FUNC(__xpg_sigpause) \
DEFINE_FUNC(__xpg_strerror_r) \
DEFINE_FUNC(xprt_register) \
DEFINE_FUNC(xprt_unregister) \
DEFINE_FUNC(__xstat) \
DEFINE_FUNC(__xstat64)

#define DEFINE_FUNC(F) int F(int x) { return x + 2; }

FUNCS

#undef DEFINE_FUNC
#define DEFINE_FUNC ,

typedef int (*funptr)(int);

funptr funcs[] = {puts FUNCS};

#undef DEFINE_FUNC

int main(void)
{
  int i = 0, x = 100;
  for (i = 0; i < sizeof(funcs)/sizeof(funcs[0]); i++)
    x = funcs[i](x);
  printf("%d\n", x);
}
